### DISCUSSION TITLE
Verbindung über BLE und RS485 nicht möglich

### DISCUSSION THREAD

**Discussion by romeox44** [syssi/esphome-jk-bms#125] [Q&A] [answered]
Hallo Zusammen, 
ich bin etwas am verzweifeln mit meinem neuen JK BMS. Weder mit einem ESP 8266 noch über ein ESP32 mit BLE bekomme ich Daten nach Home Assistent.

Ich habe das jk-BMS: JK-B1A20S15P
Hardware Vers. 10.XW
Software Vers. 10.07

Ich würde mich freuen, wenn jemand helfen kann. Ich kenne mich leider nicht wirklich mit dem ESP Home aus.
Irgendwo werde ich einen Fehler gemacht haben.

Anbei die beiden Codes:

ESP32 BLE:

```
substitutions:
  name: bms-jk
  external_components_source: github://syssi/esphome-jk-bms@main
  mac_address: C8:47:8C:F7:E6:7E
  # Defaults to "JK02". Please use "JK04" if you have some old JK-BMS version (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02

esphome:
  name: jk-bms

esp32:
  board: esp32dev
  framework:
   type: arduino


external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:

mqtt:
  broker: 192.168.178.44
  username: mqtt_user
  password: ***********
  
ota:
  password: "16f3cb661f2cb210ed37f39e4c46ff5c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Bms Fallback Hotspot"
    password: "lYasuKIuNUyf"

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0


switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"
```

Das BMS piept und es kommen folgende Meldungen:

![image](https://user-images.githubusercontent.com/93425764/172475081-c9c378d4-f75d-4f30-b11a-79eead7bf6cf.png)

ESP 8266:

```
substitutions:
  name: bms-jk
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO1
  rx_pin: GPIO3

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  baud_rate: 0

uart:
  id: uart0
  baud_rate: 115200
  rx_buffer_size: 384
  tx_pin: GPIO1
  rx_pin: GPIO3
  debug:
    direction: BOTH

#logger:
#  baud_rate: 0

# Enable Home Assistant API
api:

mqtt:
  broker: 192.168.178.44
  username: mqtt_user
  password: ***********
#  id: mqtt_client

#uart:
#  id: uart0
#  baud_rate: 115200
#  rx_buffer_size: 384
#  tx_pin: ${tx_pin}
#  rx_pin: ${rx_pin}

jk_modbus:
  id: modbus0
  uart_id: uart0

jk_bms:
  id: bms0
  jk_modbus_id: modbus0
  
binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
```

hier passiert leider nicht viel:

![image](https://user-images.githubusercontent.com/93425764/172475924-06d003c8-8d0d-4d0b-af3a-17b5cb55fee4.png)
![image](https://user-images.githubusercontent.com/93425764/172476047-d796179e-4873-488d-ad23-5f4384d77b0f.png)

Viele Grüße,
Robert

**Comment by syssi** [comment, marked as answer]
Bei der BLE-Verbindung musst du zwingend auf das Framework `esp-idf` setzen. Das Framework `arduino` crasht bei der ersten empfangenen Nachricht. Vom Crash siehst du leider nichts, weil du das Logbuch ueber WiFi konsumierst. Bitte aendere diese Zeilen:

```
esp32:
  board: esp32dev
  framework:
   type: arduino
```

in

```
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest
```

Bitte stell sicher, dass du `esphome` in der Version >2022.5.0 einsetzt, da die `mqtt`-Komponente in früheren Versionen nur mit dem Arduino-Framework kompatibel war. 

Bei deinem ESP8266-Setup mit der seriellen Verbindung ist meine Empfehlung den `logger` mit deaktivierter serieller Schnittstelle zu laden ansonsten wirst du per `api` oder `mqtt` keinen Zugriff auf das Logbuch haben. Wenn du Home Assistant einsetzt, empfehle ich dir den Einsatz der nativen API (`api`) anstatt der `mqtt`-Komponente. Diese ist wesentlich leichtgewichtiger. Ansonsten scheint hier dein WLAN etwas schwach zu sein, so dass es zu Verbindungsabbruechen kommt. Auch erkennbar ist, dass zwar Nachrichten (Request) ueber die serielle Schnittstelle rausgeschickt werden aber dein BMS nie antwortet.

Die Empfehlung bzgl. `api:` statt `mqtt:` nutzen gilt auch fuer die BLE-Konfiguration. Hier ein vollstaendiges Beispiel:

```
substitutions:
  name: bms-jk
  external_components_source: github://syssi/esphome-jk-bms@main
  mac_address: C8:47:8C:F7:E6:7E
  # Defaults to "JK02". Please use "JK04" if you have some old JK-BMS version (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02

esphome:
  name: jk-bms

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable logging
logger:

api:

ota:
  password: "16f3cb661f2cb210ed37f39e4c46ff5c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Bms Fallback Hotspot"
    password: "lYasuKIuNUyf"

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0


switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"
```

**Comment by romeox44** [comment]
Danke für die schnelle Antwort.
Wie kann ich das ESP Home updaten? Im Home Assistent habe ich eine ältere Version.
![image](https://user-images.githubusercontent.com/93425764/172480724-01c0f0c0-550b-4ac4-986c-3d04d7bd8ee5.png)


Ich sehe hier keine Update Möglichkeit.

Grüße

**Reply by syssi** [reply]
Ich nutze selbst nur den Home Assistant Core und habe deshalb wenig Erfahrungen mit Home Assistant OS + Add-ons. Ich werde morgen einmal recherchieren ob das Esphome Add-on einfach hinterher hinkt oder ob eine neue ESPHome Version auch eine neue Home Assistant Version voraussetzt. Ist dein Home Assistant Core aktuell?

**Reply by syssi** [reply]
Hier hat mir ein anderer Nutzer heute die Ursache verraten, warum der ESPHome Community Add-On nicht mehr aktualisiert wird und von einem offiziellen Add-On abgeloest wurde: https://github.com/syssi/esphome-jk-bms/issues/124#issuecomment-1149684928

**Comment by romeox44** [comment]
Wenn ich das folgende verwende
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest

 kommt bei mir immer die folgende Fehlermedung beim installieren des Projektes.
![image](https://user-images.githubusercontent.com/93425764/172481931-1b1be6e7-d258-446c-bb6f-a7d321885745.png)

Diesen Fehler habe ich auch nicht lösen können :(.

Grüße, Robert

**Reply by syssi** [reply]
Die Toolchain unter der Haube von Esphome ist aktuell nicht mit der Prozessor-Architektur des Raspberry Pi kompatibel. Es ist vermutlich einfacher, wenn du dir einen zweiten Rechner schnappst, hier Esphome in der aktuellsten Version installierst und diesen zum bauen & flashen verwendest. Die Situation wird sich bald bessern. Aktuell geht es leider nicht anders.

**Comment by romeox44** [comment]
Ist es nöglich ESP Home auf einem Windows Rechner zu installieren?

**Reply by syssi** [reply]
Ja ist es. Auf esphome.io findest du eine Installationsanleitung. Die Kurzfassung:

1. Python installieren
2. Mit Hilfe des Python Package Managers Esphome installieren: `pip install esphome`
3. Nun kannst du per `esphome run test.yaml` die Konfiguration bauen und flashen

**Reply by user0x01** [reply]
> Ist es nöglich ESP Home auf einem Windows Rechner zu installieren?

Wenn man platformio unter vs code installiert hat, kann man auch einfach die von esphoma in HassOS erzeugte Projektstruktur in VS Code complieren und mit dem esphomeflasher auf den esp brennen.

**Comment by romeox44** [comment]
Guten Morgen, 
habe ich soweit alles gemacht, jedoch kommt die folgende Fehlermeldung nahdem ich esphome run jk-bms.yaml ausführe

![image](https://user-images.githubusercontent.com/93425764/172534134-c877805f-4e70-4e7d-b870-cf603c7970da.png)

Grüße

**Reply by syssi** [reply]
Kannst du in der Liste der installierten Pakete (`pip list`) einmal pruefen, welche `platformio`- und welche `esphome`-Version installiert wurde?

**Reply by syssi** [reply]
Sorry für den Spießrutenlauf. Du bist leider bisher in jede Sackgasse gelangt die es abseits vom ausgetretenen Pfad (Linux-Maschine mit x86-Architektur) gibt.

**Comment by romeox44** [comment]
Ich habe nochmal alles neu installiert und dann ging es mit dem Code den du mir oben geschrieben hast :).
Dann habe ich die restlichen sensoren usw. aus der bsp Datei in den Code kopiert.

leider muss da irgendwo ein Fehler sein :(.
jetzt kommt:

![image](https://user-images.githubusercontent.com/93425764/172541734-b510775f-72c8-488f-865f-09aa59ebba8c.png)

hier der Code:

```
substitutions:
  name: bms-jk
  external_components_source: github://syssi/esphome-jk-bms@main
  mac_address: C8:47:8C:F7:E6:7E
  # Defaults to "JK02". Please use "JK04" if you have some old JK-BMS version (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02

esphome:
  name: jk-bms

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable logging
logger:

api:

ota:
  password: "16f3cb661f2cb210ed37f39e4c46ff5c"

wifi:
  ssid: "FRITZ!Box 7490"
  password: "37654934191012423676"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Bms Fallback Hotspot"
    password: "lYasuKIuNUyf"

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name} retrieve settings"
    retrieve_device_info:
      name: "${name} retrieve device info"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    cell_voltage_17:
      name: "${name} cell voltage 17"
    cell_voltage_18:
      name: "${name} cell voltage 18"
    cell_voltage_19:
      name: "${name} cell voltage 19"
    cell_voltage_20:
      name: "${name} cell voltage 20"
    cell_voltage_21:
      name: "${name} cell voltage 21"
    cell_voltage_22:
      name: "${name} cell voltage 22"
    cell_voltage_23:
      name: "${name} cell voltage 23"
    cell_voltage_24:
      name: "${name} cell voltage 24"
    cell_resistance_1:
      name: "${name} cell resistance 1"
    cell_resistance_2:
      name: "${name} cell resistance 2"
    cell_resistance_3:
      name: "${name} cell resistance 3"
    cell_resistance_4:
      name: "${name} cell resistance 4"
    cell_resistance_5:
      name: "${name} cell resistance 5"
    cell_resistance_6:
      name: "${name} cell resistance 6"
    cell_resistance_7:
      name: "${name} cell resistance 7"
    cell_resistance_8:
      name: "${name} cell resistance 8"
    cell_resistance_9:
      name: "${name} cell resistance 9"
    cell_resistance_10:
      name: "${name} cell resistance 10"
    cell_resistance_11:
      name: "${name} cell resistance 11"
    cell_resistance_12:
      name: "${name} cell resistance 12"
    cell_resistance_13:
      name: "${name} cell resistance 13"
    cell_resistance_14:
      name: "${name} cell resistance 14"
    cell_resistance_15:
      name: "${name} cell resistance 15"
    cell_resistance_16:
      name: "${name} cell resistance 16"
    cell_resistance_17:
      name: "${name} cell resistance 17"
    cell_resistance_18:
      name: "${name} cell resistance 18"
    cell_resistance_19:
      name: "${name} cell resistance 19"
    cell_resistance_20:
      name: "${name} cell resistance 20"
    cell_resistance_21:
      name: "${name} cell resistance 21"
    cell_resistance_22:
      name: "${name} cell resistance 22"
    cell_resistance_23:
      name: "${name} cell resistance 23"
    cell_resistance_24:
      name: "${name} cell resistance 24"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    power_tube_temperature:
      name: "${name} power tube temperature"
    state_of_charge:
      name: "${name} state of charge"
    capacity_remaining:
      name: "${name} capacity remaining"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    total_runtime:
      name: "${name} total runtime"
    balancing_current:
      name: "${name} balancing current"
    errors_bitmask:
      name: "${name} errors bitmask"

switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"
```

**Reply by syssi** [reply]
Dieser Fehler ist schnell gelöst:

```
esphome clean test.yaml
espbome run test.yaml
```

Der Clean build sollte daraufhin durchlaufen.

**Comment by romeox44** [comment]
Hier noch die installierten Pakete

```
C:\test>pip list
Package               Version
--------------------- -----------
aioesphomeapi         10.8.2
aiofiles              0.8.0
ajsonrpc              1.2.0
anyio                 3.6.1
asgiref               3.5.2
bitstring             3.1.9
bottle                0.12.21
certifi               2022.5.18.1
cffi                  1.15.0
charset-normalizer    2.0.12
click                 8.1.3
colorama              0.4.4
cryptography          3.4.8
ecdsa                 0.17.0
esp-windows-curses    0.1
esphome               2022.5.1
esphome-dashboard     20220508.0
esptool               3.3
future                0.18.2
h11                   0.13.0
idna                  3.3
ifaddr                0.1.7
kconfiglib            13.7.1
marshmallow           3.16.0
noiseprotocol         0.3.1
packaging             21.3
paho-mqtt             1.6.1
pip                   22.1.2
platformio            5.2.5
protobuf              3.20.1
pycparser             2.21
pyelftools            0.28
pyparsing             2.3.1
pyserial              3.5
pytz-deprecation-shim 0.1.0.post0
PyYAML                6.0
reedsolo              1.5.4
requests              2.27.1
semantic-version      2.9.0
setuptools            58.1.0
six                   1.16.0
sniffio               1.2.0
starlette             0.18.0
tabulate              0.8.9
tornado               6.1
tzdata                2022.1
tzlocal               4.2
urllib3               1.26.9
uvicorn               0.17.6
voluptuous            0.13.1
wheel                 0.37.1
windows-curses        2.3.0
wsproto               1.0.0
zeroconf              0.38.4
```

Grüße und Danke für deine Hilfe

Grüße Robert

**Comment by romeox44** [comment]
Hallo,

ich habe die folgenden Zeilen:
button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name} retrieve settings"
    retrieve_device_info:
      name: "${name} retrieve device info"

entfernt und dann ging es :).
Ich werde nacher noch die folgeden Befehle mit dem vollen Code probieren.
esphome clean test.yaml
espbome run test.yaml

Danke das du mir geholfen hast :). es funktioniert super!

Grüße,
Robert

**Comment by romeox44** [comment]
Ich benötige noch Hife bei einem anderen Gerät zur Regelung/Kommunikation eines Wechselrichter mit Home Assistent.
Ich habe bisher dazu noch nichts gefunden.
ich möchte über einen DPS5020 einen Wechselrichter regeln. Das funktioniert soweit seit Monaten sehr gut, jedoch kann ich nur manuell und nicht automatisch über Home Assistent regeln. 
Ich denke das würde viele interessieren, jedoch fehlen mir die Programmierkenntnisse um dies umzusetzen.

Grüße,
Robert

**Reply by syssi** [reply]
Betreibst du den DPS mit der orig. Firmware oder dieser freien Variante? https://github.com/kanflo/opendps

**Reply by syssi** [reply]
Kannst du eine neue Diskussion eröffnen, sie entsprechend benennen und ein paar Details zu seinem IST-Stand liefern? Vielleicht finden wir ja gemeinsam eine Loesung.

**Reply by romeox44** [reply]
Kann ich diese Disskussion hier unter "esphome-jk-bms" erstellen?
Kenne mich noch nicht so aus auf github.

Grüße

**Reply by romeox44** [reply]
Das DPS betreibe ich mit der originalen Firmware, habe ein USB und BLE Modul dazu.

**Reply by syssi** [reply]
Ja, ruhig hier im Projekt.

**Comment by syssi** [comment]
Ich habe die Erkenntnisse dieses Austauschs hier ergänzt: https://github.com/syssi/esphome-jk-bms/#known-issues

**Reply by romeox44** [reply]
ok super :)

**Comment by robio339** [comment]
Hi, i have same bms with same Hw and Sw version. I'm trying to connect over Bluetooth but no success. After flashing esp32 from HA esphome with esp32-ble-example.yaml (only changed mac)  I'm getting message:

```
INFO Reading configuration /config/esphome/bms-ap.yaml...
INFO Updating https://github.com/syssi/esphome-jk-bms.git@main
INFO Generating C++ source...
INFO Compiling app...
Processing bms-ap (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf 3.40302.0 (4.3.2) 
 - tool-cmake 3.16.4 
 - tool-ninja 1.7.1 
 - toolchain-riscv32-esp 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 8.4.0+2021r2-patch2
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
No dependencies
RAM:   [==        ]  16.0% (used 52368 bytes from 327680 bytes)
Flash: [=======   ]  66.5% (used 1220813 bytes from 1835008 bytes)
========================= [SUCCESS] Took 61.29 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of bms-ap.local
INFO  -> 192.168.0.202
INFO Uploading /data/bms-ap/.pioenvs/bms-ap/firmware.bin (1221200 bytes)
ERROR ESP requests password, but no password given!
```

Which password am i missing?
I have Esphome version 2022.5.1

Can you help me with this please 

Thank you in advance

Robi

**Reply by romeox44** [reply]
Guten Morgen, 
hattest du den ESP über USB am Rechner oder wolltest du über WLAN flashen? 
Ich glaube ich hatte auch mal diese Meldung beim flashen über WLAN. 
Grüße

**Reply by syssi** [reply]
Robert is right. It looks like you have passed to the `ota` component a password in the past. You have to use this password if you want to flash the node via OTA now. If you don't know the password anymore please connect & flash the ESP via a serial connection.

**Reply by robio339** [reply]
You are right. Thanks. First i flashed it over cable to get basic ble esphome code running so i could get mac address. Then i used WiFi and was searching for unknown password (unknown to me) for 3 days :). 
Thanks bout for replay and help.
Robi

**Comment by linuxdep** [comment]
Hallo,

ist das hier noch aktuell?
```
esp32:
board: esp32dev
  framework:
    type: esp-idf
    version: latest
```

ich habe es so übersetzt, läuft auch, aber ich habe noch kein BMS online... kommt die Tage, wollte es vorbereiten da es nicht im Büro steht der akku. Habe ich so irgend wo gefunden, wegen dem Stack Größen Problem... oder geht es noch besser aktuell???

```
esp32:
  board: nodemcu-32s
  variant: esp32
  framework:
    type: arduino
    version: 2.0.2
    source: https://github.com/espressif/arduino-esp32.git#2.0.2
    platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
```
