### DISCUSSION TITLE
I see no readings, how to eliminate hardware issues or find out what is wrong?

### DISCUSSION THREAD

**Discussion by Svanberg1** [syssi/esphome-jk-bms#144] [Q&A] [answered]
Hi everyone,

Super excited about this project and my JK BMS which is working like a charm, but it would be awsome if I could control it remotely  since my array is way off grid out at the family cabin and I won't be there always when its used. 

After a long wait for a JST 1.25mm pitch it finally arrived today, I am struggling to get it to work. My ESP32 is up and running after some overstack issues that I could solve (removing unnecessary sensors) -- but I don't get any readings. The log just shows an endless line of:
[01:13:34][D][uart_debug:114]: >>> 4E:57:00:13:00:00:00:00:06:03:00:00:00:00:00:00:68:00:00:01:29

Does anyone have any tips for how to find out what is wrong? One alternative is of course a hardware issue. The JST is darn small and the connection from the pins of the ESP 32 to the cable could be default (although it would surprise me). Is there any way to check this? Anyone have any other ideas?

**Comment by syssi** [comment, marked as answer]
Which JK-BMS model and version do you own? Old BMS versions are using another protocol. Could you provide a photo of your wiring? Do you own a multimeter to measure continuity?

**Reply by Svanberg1** [reply]
Of course, thanks!

This is my BMS version:
![jkbms](https://user-images.githubusercontent.com/73720585/180977546-3bab67c4-7160-4ac5-b4d5-26f274886fcf.png)

And this is my wiring:
![esp32jst](https://user-images.githubusercontent.com/73720585/180977646-e962eea8-ccbc-464b-94b9-0ae6e1b66af9.jpg)

Yes, I own a Multimeter!

Thanks!

**Reply by Svanberg1** [reply]
A close up of the pins of the esp32, green to ground, black to RX2 and yellow to TX2:
![pins](https://user-images.githubusercontent.com/73720585/180980101-ccf28d9d-8a9e-43c3-89c0-c5e7523685fd.jpg)

And my .yaml:
-----
```
esphome:
  name: jk-bms

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: "x"

ota:
  password: "x"

wifi:
  ssid: "Storstugan"
  password: "x"

  ap:
    ssid: "Jkb Fallback Hotspot"
    password: "x"

substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS via UART-TTL"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17


external_components:
  - source: ${external_components_source}
    refresh: 0s

uart:
  id: uart0
  baud_rate: 115200
  rx_buffer_size: 384
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: BOTH

jk_modbus:
  id: modbus0
  uart_id: uart0

jk_bms:
  id: bms0
  jk_modbus_id: modbus0

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"

    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    temperature_sensors:
      name: "${name} temperature sensors"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} temperature sensor temperature difference protection"
    charging_low_temperature_protection:
      name: "${name} charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} discharging low temperature recovery"

    device_address:
      name: "${name} device address"
    sleep_wait_time:
      name: "${name} sleep wait time"
    alarm_low_volume:
      name: "${name} alarm low volume"
    manufacturing_date:
      name: "${name} manufacturing date"
    total_runtime:
      name: "${name} total runtime"
    actual_battery_capacity:
      name: "${name} actual battery capacity"

text_sensor:
  - platform: jk_bms
    errors:
      name: "${name} errors"
    operation_mode:
      name: "${name} operation mode"
    battery_type:
      name: "${name} battery type"
    password:
      name: "${name} password"
    device_type:
      name: "${name} device type"
    software_version:
      name: "${name} software version"
    manufacturer:
      name: "${name} manufacturer"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
```

**Reply by syssi** [reply]
The wiring looks good to me. Could you try to swap the `rx_pin` and `tx_pin` at the config and flash again? As alternative you could swap the wires. If this doesn't work please use your multimeter to make sure `RX2` is connected to `GPIO16` (lookup the pinout of your ESP version) and `TX2` is conmected to `GPIO17`. Do you know the name of the Aliexpress seller?

**Reply by Svanberg1** [reply]
Switched the cables, and — boom — it’s working. Amazing! So many thanks!

Do you take any donations for this project? It’s so valuable!!

**Reply by syssi** [reply]
Feel free to donate a coffee! :-)

![coffee](https://user-images.githubusercontent.com/2735933/181005477-c436d725-3e99-4e02-91e6-077e2792efca.png)

**Reply by syssi** [reply]
Please keep in mind: The serial connection (UART-TTL) you are using is read-only. The only way to change settings/toggle switches is via bluetooth. This is a known limitation of the BMS firmware.

**Reply by Svanberg1** [reply]
Aha, I tried the BLE-way first, but ran into stack overflow issues and gave up. I should look into adding a BLE functionality for the switches then.

**Reply by syssi** [reply]
You could try to increase the stack size: https://github.com/syssi/esphome-jk-bms/issues/63

The drawback: The ESPHome must be flashed manually from command line. The Home Assistant UI doesn't support these advanced settings at the moment if I remember correctly.

**Reply by vrabi-cv** [reply]
> Which JK-BMS model and version do you own? Old BMS versions are using another protocol. Could you provide a photo of your wiring? Do you own a multimeter to measure continuity?

Hi there I have got same problem. Mie is advanced by the connection into the BMS. I have got only 3 pin RS 485 connection port. I have no idea which pin is what, although I have tried all combinations of cable connection, but none of them worked. I also tried to change the name of pins to GPO1 and GPIO3 as described in your sample project. Also did not work.
I attached pictures of my JK-BMS, ESP8266 mini chip, also yaml file and log file.
Any hints for connection and naming of the connection pins in yaml file?
Thanks a lot for this project as well as your help. Martin.
![IMG_20220729_153013](https://user-images.githubusercontent.com/110232498/181785346-50eb953c-0308-42c6-b4ea-c6ce63c9b86a.jpg)
![IMG_20220729_153025](https://user-images.githubusercontent.com/110232498/181785366-079a4e95-a728-488d-ba61-f89d6e9a3cbf.jpg)
![IMG_20220729_164828](https://user-images.githubusercontent.com/110232498/181785763-689f16b6-b1a4-4f3c-a68e-15042cec3f4f.jpg)

[jk-bms.yaml.txt](https://github.com/syssi/esphome-jk-bms/files/9223004/jk-bms.yaml.txt)

[logs_jk-bms_logs.txt](https://github.com/syssi/esphome-jk-bms/files/9220965/logs_jk-bms_logs.txt)

**Reply by syssi** [reply]
Your model (this is a 8S BMS version, right?) is the only JK-BMS model which has a RS485 chip onboard. You have to use a RS485 converter to talk to the RS485 port.

**Reply by syssi** [reply]
I've requested the pinout of the RS485 port at HankzorBMS Store (Aliexpress). You could order a RS485 converter module in the mean time. I prefer this board: https://raw.githubusercontent.com/syssi/esphome-jnge-mppt-controller/main/images/circuit_thumbnail.jpg

**Reply by syssi** [reply]
@EasilyBoredEngineer Could you provide the pinout of the RS485 port of your JK-B2A8S20P?

**Reply by vrabi-cv** [reply]
> I've requested the pinout of the RS485 port at HankzorBMS Store (Aliexpress). You could order a RS485 converter module in the mean time. I prefer this board: https://raw.githubusercontent.com/syssi/esphome-jnge-mppt-controller/main/images/circuit_thumbnail.jpg

Hello I found in my storage rs485 to TTL converter... Could this one be used?
![IMG_20220729_191443](https://user-images.githubusercontent.com/110232498/181810821-69b5a4fa-feb0-46a1-878f-4c1ea078253a.jpg)

**Reply by syssi** [reply]
At the moment this converter cannot be used because it requires flow control (an additional GPIO which gets pulled if the ESP wants to transmit something).

**Reply by vrabi-cv** [reply]
Could you provide me link for the necessary converter? Thanks

**Reply by syssi** [reply]
I've talked to the seller and he told me we shall use the 4pin GPS port to talk to the BMS using UART-TTL. Let's give it a try!

**Reply by vrabi-cv** [reply]
Perfect, thanks. Could you give me a hint which pins should I use and where can I find tx and rx?

**Reply by syssi** [reply]
![b2a8s20p-pinout](https://user-images.githubusercontent.com/2735933/181889312-d0aa1915-b551-4d57-b13f-6427d7e8695f.jpg)

Please don't trust this labels blindly. Could you use a multimeter and measure the voltage between the outer pins (pin 1 and 4). If the measurement is positive you can be sure about the position of VBAT and GND. VBAT must never connected to something by accident.

**Reply by vrabi-cv** [reply]
Perfect thanks. I will check the outside pins. So I will connect the V+ to the 5V on arduino or not connect this at all?

**Reply by syssi** [reply]
Never ever connect something to VBAT (it's the battery voltage. I assume ~12V in your case). You have to power your ESP with another power source / supply. Please connect RX, TX & GND only!

**Reply by vrabi-cv** [reply]
Got it. Thanks! I will give it a try and let you know.

**Reply by vrabi-cv** [reply]
Thank you so much for your patient support. After some playing with pina on my d1 mini chip I finally got the desired data! Thank you so much and enjoy a cup of coffee from me😉.  And just for info the VCC from the BMS is cca 26V. So thank you for the warning not to connect to the 8266 chip👍

**Reply by syssi** [reply]
@vrabi-cv Could you provide another esphome log containing the device info response (it arrives pretty early after boot up). I would like to know the exact model name, hardware and software version of your device. If you don't find these log messages a screenshot of the about page (android app) should be fine too.

**Reply by syssi** [reply]
@vrabi-cv friendly ping.

**Reply by vrabi-cv** [reply]
Sorry, bben out the whole day. Sending requested log, at least I hope it is what you wanted. 
[logs_jk-bms_logs.txt](https://github.com/syssi/esphome-jk-bms/files/9229616/logs_jk-bms_logs.txt)

I have another request about integration into HA. I received 2 types of devices in the HA. Both of them shows correct data, which one you recomend to keep in HA?
![HA devices](https://user-images.githubusercontent.com/110232498/182042831-2d46f7e9-59fd-486a-baf1-88586fd83b02.JPG)

**Reply by syssi** [reply]
ESPHome can talk via MQTT or the native `api` to Home Assistant. I looks like you did enable both. If you don't want to share the data without other devices I would remove the `mqtt` section from the yaml and would use the `api:` only. It's more lightweight.

**Reply by syssi** [reply]
Please disable the debug output of the `uart` component on the long run. Logging is pretty expensive.

**Reply by vrabi-cv** [reply]
Perfect thanks for advice. Everything went well and data keep comming from the BMS:). Could you give me a hint if I wanted to connect another BMS to the same d1 mini chip? Could I just add more items into the "substitutions:" - new name and new pins which belongs to the new name? THX

**Reply by syssi** [reply]
Yes, this is possible. A second instance of some components (`uart`, `jk_modbus` and `jk_bms`) is required. You have to use `ids` to connect the components properly. Ping me if you need an example. Because of the high baudrate hardware UART interfaces are recommended.

**Reply by vrabi-cv** [reply]
Hi there as I am newbie in this thing, an example would be really helpful. Could you provide me one? THX

**Reply by syssi** [reply]
How many BMS do you want to connect?

**Reply by syssi** [reply]
Your configuration yaml will look like this if you connect two JK-BMS via UART-TTL:

```
substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS via UART-TTL"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO1
  rx_pin: GPIO3
  tx_pin2: GPIO4
  rx_pin2: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.2.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:
  baud_rate: 0

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  - id: uart0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
  - id: uart1
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin2}
    rx_pin: ${rx_pin2}

jk_modbus:
  - id: modbus0
    uart_id: uart0
  - id: modbus1
    uart_id: uart1

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
  - id: bms1
    jk_modbus_id: modbus1

binary_sensor:
  - platform: jk_bms
    jk_bms_id: bms0
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    # ...

  - platform: jk_bms
    jk_bms_id: bms1
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    # ...

sensor:
  - platform: jk_bms
    jk_bms_id: bms0
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    # ...

  - platform: jk_bms
    jk_bms_id: bms1
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    # ...
```

**Reply by vrabi-cv** [reply]
Thank you so much! Works just perfectly. Enjoy another cup of coffee:) Martin

**Reply by syssi** [reply]
Thanks! Please keep in mind: The number of hardware UART interfaces of a ESP8266 are very limited. If you use GPIO4/GPIO5 a software implementation is used which doesn't perform well on high baudrates. If your setup doesn't work reliable please migrate to an ESP32 because this microcontroller provides three hardware UARTs.

**Reply by vrabi-cv** [reply]
Hi there not everything is perfect:( I connected both BMS and data are comming, but I cannot read both, because after 1st BMS I got immediatelly data for 2nd and those data stays active:
[17:25:29][I][jk_bms:062]: Status frame received
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 1': Sending state 3.40100 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 2': Sending state 3.40200 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 3': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 4': Sending state 3.40500 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 5': Sending state 3.40000 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 6': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 7': Sending state 3.40200 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms cell voltage 8': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms min cell voltage': Sending state 3.40000 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms max cell voltage': Sending state 3.40500 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms delta cell voltage': Sending state 0.00500 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms average cell voltage': Sending state 3.40237 V with 3 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms power tube temperature': Sending state 30.00000 °C with 0 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms temperature sensor 1': Sending state 30.00000 °C with 0 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms temperature sensor 2': Sending state 28.00000 °C with 0 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms total voltage': Sending state 27.22000 V with 2 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms current': Sending state 0.50000 A with 2 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms power': Sending state 13.61000 W with 2 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms charging power': Sending state 13.61000 W with 2 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms discharging power': Sending state 0.00000 W with 2 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms capacity remaining': Sending state 99.00000 % with 0 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms charging cycles': Sending state 24.00000  with 0 decimals of accuracy
[17:25:29][D][sensor:126]: 'jk-bms actual battery capacity': Sending state 256.00000 Ah with 0 decimals of accuracy
[17:25:29][D][text_sensor:067]: 'jk-bms manufacturer': Sending state **_### 'Input UserdaPrvni set 24'_**
[17:25:29][D][sensor:126]: 'jk-bms protocol version': Sending state 1.00000  with 0 decimals of accuracy
[17:25:31][I][jk_bms:062]: Status frame received
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 1': Sending state 3.40200 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 2': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 3': Sending state 3.40100 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 4': Sending state 3.40200 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 5': Sending state 3.39800 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 6': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 7': Sending state 3.40200 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms cell voltage 8': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms min cell voltage': Sending state 3.39800 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms max cell voltage': Sending state 3.40300 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms delta cell voltage': Sending state 0.00500 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms average cell voltage': Sending state 3.40175 V with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms current': Sending state 1.48000 A with 2 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms power': Sending state 40.27080 W with 2 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms charging power': Sending state 40.27080 W with 2 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms discharging power': Sending state 0.00000 W with 2 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms capacity remaining': Sending state 100.00000 % with 0 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms charging cycles': Sending state 6.00000  with 0 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms total charging cycle capacity': Sending state 1792.00000 Ah with 0 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms errors bitmask': Sending state 0.00000  with 0 decimals of accuracy
[17:25:31][D][text_sensor:067]: 'jk-bms errors': Sending state ''
[17:25:31][D][sensor:126]: 'jk-bms current calibration': Sending state 1.23400 A with 3 decimals of accuracy
[17:25:31][D][sensor:126]: 'jk-bms total runtime': Sending state 234.66667 h with 0 decimals of accuracy
[17:25:31][D][text_sensor:067]: 'jk-bms total runtime formatted': Sending state '9d 18h'
[17:25:31][D][sensor:126]: 'jk-bms actual battery capacity': Sending state 256.00000 Ah with 0 decimals of accuracy
[17:25:31][D][text_sensor:067]: 'jk-bms manufacturer': Sending state **### 'Input UserdaDruhy set 24'**
[17:25:31][D][sensor:126]: 'jk-bms protocol version': Sending state 1.00000  with 0 decimals of accuracy
[17:25:36][I][jk_bms:062]: Status frame received

**Reply by syssi** [reply]
Could you provide your config yaml? I would like to reproduce the issue. Did you wire all IDs correctly?

**Reply by vrabi-cv** [reply]
Here it is
[ESPhome program_wemos D1mini_2x24V.txt](https://github.com/syssi/esphome-jk-bms/files/9409397/ESPhome.program_wemos.D1mini_2x24V.txt)

**Reply by syssi** [reply]
We should name the sensors / entities properly. Could you try something like this:

```
substitutions:
  name: jk-bms
  name_bms0: "${name} bms0"
  name_bms1: "${name} bms1"
  device_description: "Monitor and control a JK-BMS via UART-TTL"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO1
  rx_pin: GPIO3
  tx_pin2: GPIO4
  rx_pin2: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.2.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:
  baud_rate: 0

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  - id: uart0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
  - id: uart1
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin2}
    rx_pin: ${rx_pin2}

jk_modbus:
  - id: modbus0
    uart_id: uart0
  - id: modbus1
    uart_id: uart1

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
  - id: bms1
    jk_modbus_id: modbus1

binary_sensor:
  - platform: jk_bms
    jk_bms_id: bms0
    balancing:
      name: "${name_bms0} balancing"
    charging:
      name: "${name_bms0} charging"
    # ...

  - platform: jk_bms
    jk_bms_id: bms1
    balancing:
      name: "${name_bms1} balancing"
    charging:
      name: "${name_bms1} charging"
    # ...

sensor:
  - platform: jk_bms
    jk_bms_id: bms0
    total_voltage:
      name: "${name_bms0} total voltage"
    current:
      name: "${name_bms0} current"
    power:
      name: "${name_bms0} power"
    # ...

  - platform: jk_bms
    jk_bms_id: bms1
    total_voltage:
      name: "${name_bms1} total voltage"
    current:
      name: "${name_bms1} current"
    power:
      name: "${name_bms1} power"
    # ...
```
