### DISCUSSION TITLE
How to disable debug mode?

### DISCUSSION THREAD

**Discussion by pato-loco** [syssi/esphome-jk-bms#198] [Q&A] [answered]
Hi,

In less then 3h I´ve got over 350.000 messages from the es-home-jk-bms on my MQTT broker.
Is it possible to disable the debug mode that there are no more messages forwarded to the /debug topic?
And is it possible to keep the query interval variable?

Thanks in advance!

**Comment by syssi** [comment, marked as answer]
You can control the log level globally and per component:

```
logger:
  level: DEBUG
  logs:
    api.service: WARN
    ota: WARN
    wifi: WARN
    sensor: DEBUG
    jk_bms_ble: INFO
```

I assume you are looking for something like this:

```
logger:
  level: ERROR
```

See https://esphome.io/components/logger.html

**Reply by syssi** [reply]
Another idea is to change the behavior of the `mqtt` component to keep the log messages locally:

```
mqtt:
  log_topic: "debug"
    level: ERROR
```

The configuration above is untested/guessed using the documentation: https://esphome.io/components/mqtt.html

**Reply by syssi** [reply]
Another important detail: The notification interval of the JK-BMS is static and cannot be changed (1-2 messages per second). The component can be configured to throw away most of the traffic/notifications/readings using the throttle option:

```
jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 10s
    id: bms0
```
