### DISCUSSION TITLE
Der richtige Steckertyp

### DISCUSSION THREAD

**Discussion by salequevale** [syssi/esphome-jk-bms#2] [Q&A] [answered]
Hallo Zusammen,

in der Anleitung steht man braucht ein (JST-SH 1.0mm pinch) Kabel. 

ich habe in ebay folgendes gekauft welches leider nicht passt:
Steckergröße: SH 1.0mm 4 Pin, Stückzahl / Paar: 1, Variante: Stecker / Kabel einzeln 
https://www.ebay.de/itm/184116829558?hash=item2ade37dd76:g:ReMAAOSwYDNgo4kM

Kann mir bitte eine passende Bezugsquelle nennen ?

Besten Dank !

**Comment by syssi** [comment, marked as answer]
Du hast leider Recht. Ich war mir bei der Recherche unsicher und habe daraufhin bei Aliexpress beim gleichen Haendler sowohl eine Packung SH 1.0mm als auch eine Packung JST 1.25mm bestellt. Die beiden Tüten waren nicht weiter beschriftet und ich habe mich lediglich gefreut, dass ich richtig geraten habe. Wenn ich den Inhalt nun genauer vergleiche, dann entspricht der JST 1.25mm mehr dem Original, welchen ich vom orig. RS485-Adapter abgeschnitten habe. Ich schick dir einen Brief mit dem richtigen Stecker, wenn du magst.

**Comment by salequevale** [comment]
Danke für die schnelle Antwort und dein Angebot. Ich würde das gerne in Anspruch nehmen und auch für die Unkosten aufkommen. Will ja schliesslich deine Lösung nachbauen ;-)

Wie machen wir das mit der Adresse ? Die wird hier doch dann
veröffentlicht, oder ? Ich bin erst seit kurzem hier angemeldet...

**Reply by syssi** [reply]
Wenn du dieses Repository clonst per "git clone" findest du im "git log" meine E-Mail-Adresse. Schreib mir per Mail deine Adresse, dann geht das Kabel auf den Weg.

**Comment by JakobTewes** [comment]
Heyhey,

coole Nummer dieses Projekt! Habt Ihr mir bitte ein Photo von dem Stecker? Würde gerne den original rs485 vermeiden :). Korrekt, dass es der JST 1,25mm ist? Dreipolig?

**Reply by syssi** [reply]
4 polig. Schau einmal hier: https://github.com/syssi/esphome-jk-bms#schematics

**Comment by JakobTewes** [comment]
wer lesen kann, ist klar im Vorteil 🫣. Dankeschön 👍

**Reply by syssi** [reply]
Welches BMS Model planst du anzusprechen? Es gibt ein neues 4S Model, welches voraussichtlich mit nativem RS485 daher kommt. Alle anderen Versionen haben TTL am UART-/GPS-Port anliegen.

**Comment by JakobTewes** [comment]
Och du...."ganz klassisch" 😜:

- JK-B2A24S20P (würdest du mir für "lokale Visualiserung" das LCD Display empfehlen?)
- 16x280AH LiFePo4
- MPP MPI 15KW (new Gen mit rundem Display - geht das schon mit Deinem "mpp-solar"?)

Sorry für die Neugier und schöne Grüße vom Bodensee

**Reply by syssi** [reply]
Das B2A24S20P ist erprobt insbesondere in den aktuelleren Hardware-Versionen. Das Display hatte ich selbst noch nie in der Hand. Ich denke es hängt ganz von dir ab. Ich warte noch auf die Bestätigung des Verkäufers, dass man UART- und Display-Port gleichzeitig nutzen kann. Der Mikrocontroller auf dem BMS hat grundsätzlich 3 UARTs (= Bluetooth, RS485/TTL, Display) aber mein weiss ja nie.

Bei den PIP-Invertern fehlt mir leider jegliche Übersicht, welche Ausprägungen/Modelle mit welchen Software-Versionen es so gibt. Ein Versuch ist es auf jeden Fall wert und wenn etwas fehlt, ist es schnell angepasst.

**Reply by JakobTewes** [reply]
Ah...dann bestelle ich das Display wohl lieber nicht 😜. Lässt Du mich bitte wissen, wenn du Antwort zur gleichzeitigen Verbindung hast?

Projekt braucht noch etwas...MPP hat 50 Tage als Lieferzeit angegeben 🙄.

Habe das Gefühl, wir schreiben uns wieder - solange vielen Dank Dir schonmal für Deine Aufwände und das Teilen Deiner Arbeit 👍

**Reply by syssi** [reply]
Das kleine Display kann gleichzeitig mit einer "RS485"/UART-TTL-Verbindung betrieben werden. Das große Display hat scheinbar zwei Anschlusskabel und wird neben dem Display-Port auch an den RS485-Port angeschlossen. Voraussichtlich um dort seinen Strom zu beziehen. Weil der RS485-Port dann belegt ist, steht in der Artikelbeschreibung: Kein Parallelbetrieb.

**Reply by silvermd** [reply]
Ah danke für die info... das hab ich noch nicht gewusst.

**Comment by BobbyDD** [comment]
Hallo,
ich muss das Thema noch mal aufgreifen. Ich seh bei den JST Stecker nicht mehr durch.
Kann mir bitte jemand die genaue Bezeichnung für den 4 poligen GPS und den 6 poligen Display Stecker sagen?
Danke

**Reply by syssi** [reply]
GPS-Port ist 4 Pin, JST 1.25mm pitch. Siehe https://github.com/syssi/esphome-jk-bms#schematics
Display-Port ist abhängig vom Modell siehe: https://github.com/syssi/esphome-jk-bms/blob/main/docs/display-port.md

**Reply by BobbyDD** [reply]
Vielen Dank

**Comment by concierge-at** [comment]
Hallo, ich bin nun auch seit einem halben Jahr am basteln und der Erfolg is mäßig. Ich versuche jede Fehlerquelle zu entwirren um herauszufinden wo es hakt. 
ich hab mir die 4pol jst1.25 besorgt. am esp angelötet und dann die Buchse gesucht wo du Als Rs485 angibst doch der 4 Polige passt bei mir nur in die GPS Buchse und der Original rs485 auch.

Ich hab den ESP geflasht, mit dem wlan verbunden, Dann am BMS angesteckt und den Strom dazu. Es liefen dann im Esphome wlan logg viele bunte Zeilen doch im Dashboard von Dr3amer kam keine anzeige an.

Ich habe MQTT der server sollte eigentlich funktionieren am HA, beim API werd ich nicht schlau da da kein key steht :/ 

Wie könnte ich den fehler eingrenzen und suchen. 
Danke im voraus

**Reply by concierge-at** [reply]
Hello dnwalker, I don't know which language you speak, I use google translator German English. I'm a complete beginner on esp Esphome and Homeassistant.
Why do I want to go via cable? Because I've read in several places that the BT connection breaks down very often and the setup shouldn't be that easy.

I have an HA installed with MQTT and mqtt explorer, as well as tailscale because I need remote access. You write connection to the BMS, I can't check that, the BMS and the inverter are a good hour's drive away from me

I see some topics in the esp's mqtt exploret, these have no values ​​because the BMS is not connected
You are writing about a web interface, how can I incorporate that into my yaml?

I'm attaching my yaml

`#JK-BMS via UART-TTL
#esphome:
  #name: jk-bms-mqtt
  #friendly_name: JK-BMS-MQTT

#esp32:
  #board: esp32dev
  #framework:
    #type: arduino

substitutions:
  name: jk-bms
  device_description: "Monitor a JK-BMS via UART-TTL"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0

esp32:
  #board: wemos_d1_mini32
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

jk_modbus:
  - id: modbus0
    uart_id: uart_0
    rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
    update_interval: 5s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"
    online_status:
      name: "${name} online status"
    #emergency_switch:
      #name: "${name} emergency switch"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    power_tube_temperature:
      name: "${name} power tube temperature"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    capacity_remaining:
      name: "${name} capacity remaining"
    capacity_remaining_derived:
      name: "${name} capacity remaining derived"
    temperature_sensors:
      name: "${name} temperature sensors"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    battery_strings:
      name: "${name} battery strings"
    errors_bitmask:
      name: "${name} errors bitmask"
    operation_mode_bitmask:
      name: "${name} operation mode bitmask"
    total_voltage_overvoltage_protection:
      name: "${name} total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      name: "${name} total voltage undervoltage protection"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      name: "${name} cell pressure difference protection"
    discharging_overcurrent_protection:
      name: "${name} discharging overcurrent protection"
    discharging_overcurrent_delay:
      name: "${name} discharging overcurrent delay"
    charging_overcurrent_protection:
      name: "${name} charging overcurrent protection"
    charging_overcurrent_delay:
      name: "${name} charging overcurrent delay"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      name: "${name} charging high temperature protection"
    discharging_high_temperature_protection:
      name: "${name} discharging high temperature protection"
    charging_low_temperature_protection:
      name: "${name} charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} discharging low temperature recovery"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    current_calibration:
      name: "${name} current calibration"
    device_address:
      name: "${name} device address"
    sleep_wait_time:
      name: "${name} sleep wait time"
    alarm_low_volume:
      name: "${name} alarm low volume"
    manufacturing_date:
      name: "${name} manufacturing date"
    total_runtime:
      name: "${name} total runtime"
#    start_current_calibration:
#      name: "${name} start current calibration"
    actual_battery_capacity:
      name: "${name} actual battery capacity"
#    protocol_version:
#      name: "${name} protocol version"

switch:
  - platform: jk_bms
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

text_sensor:
  - platform: jk_bms
    errors:
      name: "${name} errors"
    operation_mode:
      name: "${name} operation mode"
    battery_type:
      name: "${name} battery type"
    password:
      name: "${name} password"
    device_type:
      name: "${name} device type"
    software_version:
      name: "${name} software version"
    manufacturer:
      name: "${name} manufacturer"
    total_runtime_formatted:
      name: "${name} total runtime formatted"`

and currently I can't get the balancing switch into the dashboard

In any case, thank you for the help and I am really grateful for any help I get

**Reply by concierge-at** [reply]
Hallo @ dnwalker, danke für deine ausführung, das ist das informativste seit wochen danke dir.

Ich verwende ein B2A24S15P, an einer 16s batterie.
Würdest du mir deine yaml eventuell zur verfugung stellen denn die läuft auch, das wäre spitzenklasse.
Dann macht also ein esp BT und wlan das ist ja irre. Und das bms kann ich per wlan dann mit bt verbinden wegen password und so.?
Welches dashboard verwendest du zum anzeigen. Und kann mann auch werte aufzeichnen also für kurven zur analyse. Ich weis ich hab fragen über fragen.

Ich danke dir schon mal für die grosse hilfe und schöne grüsse aus Österreich

**Reply by concierge-at** [reply]
Hallo danke, ja ich bin auch gespannt, 
Die mac adresse vom bms kann ich die in der app auslesen?  Leider hab ich vor einem jahr das Standard Passwort schon ersetzt.
Aber alleine eine funktionierende config zu haben wo man nachsehen kann ist ja schon viel wert.
Leider steht das alles eine autostunde von mir weg ich hab zwar laptop mit aber 
Warten wirs mal ab was ich schaffe. 
Ich hab neue esp32dev hier da flash ich mir einen 
Eventuell komm ich am wochenende hin. Auf jedenfall ich halte dich auf dem laufenden.
Kann man sich hier auch mit PN austauschen? 
Danke und einen schönen Tag noch

**Reply by concierge-at** [reply]
Dann hatte ich richtig glück das du über meine worte gestolpert bist und auch noch versuchst zu helfen.
Ich versuche samstag alles umzusetzen wenns klappt werd ichs vermelden und wenn nicht natürlich auch.
Wegen pn fragte ich nur für den fall das ich wo hänge und dich direkt hatte fragen können ohne hier alles zuzuschreiben🫣😀
Danke und alles gute und bis bald

**Reply by concierge-at** [reply]
hallo dnwalker, okay das mit email verstehe ich. ich hab auch die benachrichtigung drinnen und sehe gleich wenn jemand antwortet.
eventuell kommen wir ja so zusammen :) danke schon mal für die großartige Hilfestellung

so es hat etwas gedauert bis ich deinen code auf meinen esp gebracht habe
ich musste ein paar Sektionen aus kommentieren.
Zelle 9-16 hab ich eingefügt 

Achso danke das mit dem web is spitze da sieht man gleich was sache ist. das hilft mir glaube ich am meisten danke für den super tipp

Das mit den LED musste ich auskommentieren da hat ESPhome immer gespuckt
Wegen dem BT password für das BMS wo kommt das hin?
Wegen dem API key welcher ist das wie komme ich zu dem 
wegen dem OTA key welcher ist das und wie komme ich zu dem 
und soll ich nun MQTT machen oder weglassen?

Danke im voraus

```
#esphome:
  #name: jk-bt
  #friendly_name: jk-BT

substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main

  mac_address: !secret mac_bms

  # Defaults to "JK02" (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  #protocol_version: JK02
  protocol_version: JK02_32S

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.5.0

esp32:
  #board: wemos_d1_mini32
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  #password: "natürlich geheim"
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
# Optional manual IP
  manual_ip:
    static_ip: 192.168.0.210
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Bms-Bluetooth"
    password: "12345678"

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: geheim  


 


esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("JK-", 0) == 0) {
            ESP_LOGI("ble_adv", "New JK-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    online_status:
      name: "${name} online status"


button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name} retrieve settings"
    retrieve_device_info:
      name: "${name} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${name} balance trigger voltage"
    cell_count:
      name: "${name} cell count"
    total_battery_capacity:
      name: "${name} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    voltage_calibration:
      name: "${name} voltage calibration"
    current_calibration:
      name: "${name} current calibration"
    power_off_voltage:
      name: "${name} power off voltage"
    max_balance_current:
      name: "${name} max balance current"
    max_charge_current:
      name: "${name} max charge current"
    max_discharge_current:
      name: "${name} max discharge current"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
      id: v1
    cell_voltage_2:
      name: "${name} cell voltage 2"
      id: v2
    cell_voltage_3:
      name: "${name} cell voltage 3"
      id: v3
    cell_voltage_4:
      name: "${name} cell voltage 4"
      id: v4
    cell_voltage_5:
      name: "${name} cell voltage 5"
      id: v5
    cell_voltage_6:
      name: "${name} cell voltage 6"
      id: v6
    cell_voltage_7:
      name: "${name} cell voltage 7"
      id: v7
    cell_voltage_8:
      name: "${name} cell voltage 8"
      id: v8
    cell_voltage_9:
      name: "${name} cell voltage 9"
      id: v9    
    cell_voltage_10:
      name: "${name} cell voltage 10"
      id: v10
    cell_voltage_11:
      name: "${name} cell voltage 11"
      id: v11
    cell_voltage_12:
      name: "${name} cell voltage 12"
      id: v12
    cell_voltage_13:
      name: "${name} cell voltage 13"
      id: v13
    cell_voltage_14:
      name: "${name} cell voltage 14"
      id: v14
    cell_voltage_15:
      name: "${name} cell voltage 15"
      id: v15
    cell_voltage_16:
      name: "${name} cell voltage 16"
      id: v16
    
    cell_resistance_1:
      name: "${name} cell resistance 1"
    cell_resistance_2:
      name: "${name} cell resistance 2"
    cell_resistance_3:
      name: "${name} cell resistance 3"
    cell_resistance_4:
      name: "${name} cell resistance 4"
    cell_resistance_5:
      name: "${name} cell resistance 5"
    cell_resistance_6:
      name: "${name} cell resistance 6"
    cell_resistance_7:
      name: "${name} cell resistance 7"
    cell_resistance_8:
      name: "${name} cell resistance 8"
    cell_resistance_9:
      name: "${name} cell resistance 9"
    cell_resistance_10:
      name: "${name} cell resistance 10"
    cell_resistance_11:
      name: "${name} cell resistance 11"
    cell_resistance_12:
      name: "${name} cell resistance 12"
    cell_resistance_13:
      name: "${name} cell resistance 13"
    cell_resistance_14:
      name: "${name} cell resistance 14"
    cell_resistance_15:
      name: "${name} cell resistance 15"
    cell_resistance_16:
      name: "${name} cell resistance 16"
    total_voltage:
      name: "${name} total voltage"
      id: total_voltage
    current:
      name: "${name} current"
      id: current
    power:
      name: "${name} power"
      id: power
    charging_power:
      name: "${name} charging power"
      id: charging_power
    discharging_power:
      name: "${name} discharging power"
      id: discharging_power
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
      id: temp1
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
      id: temp2
    power_tube_temperature:
      name: "${name} power tube temperature"
    state_of_charge:
      name: "${name} state of charge"
      id: state_of_charge
    capacity_remaining:
      name: "${name} capacity remaining"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    total_runtime:
      name: "${name} total runtime"
    balancing_current:
      name: "${name} balancing current"
    errors_bitmask:
      name: "${name} errors bitmask"

  - platform: wifi_signal
    name: "WiFi jk-bms-BT"
    update_interval: 60s  
    id: wifisignal

  

switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

    
  - platform: restart
    name: "jk-bms Restart"

  #- platform: gpio
    #pin: 2
    #id: WlanLed # die ID kann optional vergeben werden
    #name: "Wlan Led JK-bms"
    #disabled_by_default: true
    #internal: true
    #inverted: false
  

text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "${name} errors"
    total_runtime_formatted:
      name: "${name} total runtime formatted"


#interval:
  #- interval: 5s
    #then:
      #if:
        #condition:
          #wifi.connected:
        #then:
          #- switch.turn_on: WlanLed
        #else:
          #- switch.turn_off: WlanLed
``` 
`code code`
