### DISCUSSION TITLE
Home Assistant - Yaml check

### DISCUSSION THREAD

**Discussion by lycaki** [syssi/esphome-jk-bms#222] [Q&A] [answered]
Hi Everyone,

I thought I was doing well but I can't get any RX/TX data out of the ESP2866 mini

I can see this in my MQTT data 

```
name_cell_voltage_1
name_cell_voltage_2
name_cell_voltage_3
name_cell_voltage_4
name_cell_voltage_5
name_cell_voltage_6
name_cell_voltage_7
name_cell_voltage_8
name_min_voltage_cell
name_total_voltage
name_capacity_remaining_derived
name_cell_voltage_overvoltage_recovery
name_cell_pressure_difference_protection
name_charging_overcurrent_delay
name_temperature_sensor_temperature_recovery
name_discharging_low_temperature_protection
name_current_calibration
name_manufacturing_date
name_max_cell_voltage
name_min_cell_voltage
name_max_voltage_cell
name_temperature_sensor_2
name_power
name_capacity_remaining
name_total_charging_cycle_capacity
name_operation_mode_bitmask
name_cell_voltage_overvoltage_protection
name_balance_starting_voltage
name_power_tube_temperature_recovery
name_temperature_sensor_temperature_difference_protection
name_charging_low_temperature_protection
name_total_battery_capacity_setting
name_alarm_low_volume
name_temperature_sensor_1
name_total_voltage_overvoltage_protection
name_cell_voltage_undervoltage_delay
name_charging_overcurrent_protection
name_power_tube_temperature_protection
name_charging_high_temperature_protection
name_device_address
name_average_cell_voltage
name_delta_cell_voltage
```

No values though, I can also similar headings in ESPHOME part of HomeAssistant

Does anyone have a copy of their Yaml code for HomeAssistant I can copy/look at?

Thanks

Below is my Yaml code, any glaring errors - it's possible the RX/TX part of the UART are not working... but this seemed more unlikely

```
external_components:
  - source: github://syssi/esphome-jk-bms@main


esphome:
  name: jk-bms

  

esp8266:
  board: d1_mini

# Enable logging
logger: 
    baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "removed"

ota:
  password: "removed"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jk-Bms Fallback Hotspot"
    password: "removed"

captive_portal:

uart:
  id: uart0
  baud_rate: 115200
  rx_buffer_size: 384
  tx_pin: GPIO1
  rx_pin: GPIO3

mqtt:
  broker: 192.168.0.179
  username: username (removed)
  password: password (removed)


jk_modbus:
  id: modbus0
  uart_id: uart0
  rx_timeout: 50ms

jk_bms:
  id: bms0
  jk_modbus_id: modbus0

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
```
