### DISCUSSION TITLE
Code Extension handle "gpio"

### DISCUSSION THREAD

**Discussion by dossidr** [syssi/esphome-jk-bms#246] [Q&A]
Hello experts

My idea about this code:
1. I want to monitor the cell voltage values ​​for a lower and upper threshold. The value range OORHIgh or OORLow should switch a battery contactor ON or OFF.
For this I would have to have an array, which is always filled with the respective cell voltage and this is compared. Then the control of a contactor should be derived from this, which in turn is connected to a digital output of the ESP32.

2. When the ESP is rebooted, a precharge phase must control the bypass of the contactor, i.e. a second digital output.
The problem with this: I tried to define the [platform: gpio] in *.yaml in order to use the digital in and output. Unfortunately, I can't do that because the entire BLE tracker maps the loop. And this is defined.
So what do I have to do to implement my feature and in which area of ​​the code do I have to do it? I assume that the *.yaml file that I flash onto the ESP only represents the definition of the individual parameters. ESPhome is new to me. I wrote my code in C for an Arduino. This is based on the structure of 4 ADC [ADS1115]. However, since this structure leads to a great deal of cabling, I would like to use the code published here for the NEEY. At the moment I have only attached the BLE Tracker code to MQTT to see how stable this connection is, because I need a permanent connection without interruption, which leads me to the next question...

3. From your point of view, does it even make sense to use the BLE To permanently connect the tracker, at the risk that the wireless connection is not a cable connection. In other words, how robsut is it in continuous use.... I have attached my Arduino code which is currently based on 4x ADC ergo 16 channels. What you don't need within the BLE Tracker...

best regards denny

[I2C_NANO_IOT_read_16Ch_V1.7.ino.zip](https://github.com/syssi/esphome-jk-bms/files/10713017/I2C_NANO_IOT_read_16Ch_V1.7.ino.zip)

**Comment by syssi** [comment]
1. Feel free to extend the YAML configuration. It looks like you want to add a `switch` using the `gpio` platform:

```
switch:
  - platform: gpio
    id: battery_contactor
    pin: GPIO25
    name: "Battery contactor"
  - platform: gpio
    id: precharge_contactor
    pin: GPIO26
    name: "Precharge contactor"
```
https://esphome.io/components/switch/gpio.html

As next step you could extend one of the `heltec_balancer_ble` sensors by adding a `on_value` or `on_value_range` instruction:

``` 
sensor:
  - platform: heltec_balancer_ble
    min_voltage_cell:
      name: "${name} min voltage cell"
    on_value_range:
      - below: 2.85
        above: 3.6
        then:
          - switch.turn_off: battery_contactor
```
https://esphome.io/components/sensor/index.html#on-value

2. You could use a pulldown to turn off the battery contactor per default. At the `esphome` section you can add `on_boot` instructions:

```
esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.3.0
  on_boot:
    then:
      - light.turn_on: precharger_contactor
      - delay: 10s
      - light.turn_on: battery_contactor
```
https://esphome.io/components/esphome.html

3. I prefer wired connections over BLE connections. If NEEY / HankzorBMS responds to your "how to use the pin header for wired communication" request I would be happy to implement UART communication for the NEEY balancer.

**Reply by dossidr** [reply]
Hello Sebastian.... Point 3.
Yes i hope the company will getting answer... but i think its not possible current.... By the way.. you confitm my mindset to be handle communication... Your implementation is absolut awesome and many stuff included to read any data from balancer on BLE... but i think for 100% stable 365/24 it will be nessesary a wire connection is the best way... and thats the reason by my first idea implemt on Arduino on external ADC (ADS1115), but measurment w/ battery pack to be handle single cell its not so easy. I have a idea to be resolve that use a flip switch function  w/ SSR Board and on output to ADC w/ two rails as connection on ADC [A0 <--> A1] differential measurement at runtime.... so im not sure whats the best way for my scenario.... im develop :-)

**Comment by dossidr** [comment]
Hi Sebastian
Many Thanks for your naswer but the compilation is failed about these implemenatation:
`switch:
  - platform: heltec_balancer_ble
    balancer:
      name: "${name} balancer"
  - platform: gpio
    id: battery_contactor
    pin: GPIO25
    name: "Battery contactor"
  - platform: gpio
    id: precharge_contactor
    pin: GPIO26
    name: "Precharge contactor"`

Compilation Error:

`Processing heltec-balancer (board: wemos_d1_mini32; framework: espidf; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40402.0 (4.4.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
No dependencies
Compiling .pioenvs/heltec-balancer/src/main.o
Linking .pioenvs/heltec-balancer/firmware.elf
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/heltec-balancer/src/main.o:(.literal._Z5setupv+0x374): undefined reference to `vtable for esphome::gpio::GPIOSwitch'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/heltec-balancer/src/main.o:(.literal._Z5setupv+0x378): undefined reference to `vtable for esphome::gpio::GPIOSwitch'
collect2: error: ld returned 1 exit status
*** [.pioenvs/heltec-balancer/firmware.elf] Error 1
========================= [FAILED] Took 333.70 seconds =========================`

I dont know why is broken compilation w/ "undefined reference to `vtable for esphome::gpio::GPIOSwitch'"
Did anybody know these Issue?

best regards denny

Update:

and any test to be define an additional "switch" is not working as well because switch component is getting an Error  duplicate implementation... see picture attached...
And this is the point to worry my extension idea..... 
Where is the right code position to be extent the original *.yaml w/ base component from ESPHome?

best regards denny
![Bildschirmfoto zu 2023-02-11 14-54-48](https://user-images.githubusercontent.com/45298863/218261950-a363a31c-70c8-4acc-a3e9-81315b10d9ad.png)

**Reply by syssi** [reply]
Please provide your full YAML. The switch sections must be merged into one block.

**Reply by syssi** [reply]
If you see a build error please do a clean build:

```
esphome clean yourconfig.yaml
esphome run yourconfig.yaml
```

**Reply by dossidr** [reply]
Hi Sebastian
Yes absolut... after cleanup build successful and flashed included extensions.... tomorrow i try check to be handle GPIO Hardware conncetion to these code....
[heltec-balancer_GPIO.yaml.zip](https://github.com/syssi/esphome-jk-bms/files/10713933/heltec-balancer_GPIO.yaml.zip)
many thanks for your support....
But one think i have been fixed.....
Thats not light --> switch otherwise declaration failed..... reference is switch area... 
YAML file attached...
```
   on_boot:
    then:
      - light.turn_on: precharger_contactor
      - delay: 10s
      - light.turn_on: battery_contactor`
```

best regards denny
