### DISCUSSION TITLE
(Charge, Discharge, Balancing) Controls not showing up as switches in Homeassistant

### DISCUSSION THREAD

**Discussion by PMPoulsen** [syssi/esphome-jk-bms#261] [Q&A] [answered]
Hi,

I have integrated theBMS UART with an ESP32 Devboard through ESPHome in Homeassistant: I have connection to the BMS and getting data, I am however not able to control the Charge, Discharge, Balancing switches.

In the YAML code the entities are declared as binary_sensors:
binary_sensor:

```
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"
```

The above is a copy from the example code in this git repository, and the result is E.g:
![image](https://user-images.githubusercontent.com/46517931/220936094-d354dd35-744e-4982-920f-3f1cf08e7055.png)

and not a control (switch) that I can toggle (on/off)

Then I tried to declare the switches like this, but then the ESPHome will not compile:

```
#switch:
#  - platform: jk_bms
#    balancing_switch:
#      name: "${name} balancing switch"
#    charging_switch:
#      name: "${name} charging switch"
#    discharging_switch:
#      name: "${name} discharging switch"
```

What am I doing wrong or missing?
Any guidance would be helpfull, thanks in advance
