### DISCUSSION TITLE
jk-bms and heltec ESP32 Display

### DISCUSSION THREAD

**Discussion by riker65** [syssi/esphome-jk-bms#263] [Q&A]
Hi

anyone tried a heltec ESP32 with display?

maybe some templates available?

Thanks

**Comment by syssi** [comment]
You could try to port this solution: https://github.com/syssi/esphome-jbd-bms#goodies

**Comment by riker65** [comment]
will check thanks

**Comment by riker65** [comment]
Hi,
after checking this, I tried to compile this 


in general -other project -the esp32 heltec is working when I use this setting:

```
esp32:
#  board: wemos_d1_mini32
#  platform: ESP32
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
 #https://github.com/esphome/issues/issues/3580    `



but after compiling I get an error starting it.

maybe you have an idea? 

`
Hard resetting via RTS pin...
INFO Successfully uploaded program.
INFO Starting log output from COM9 with baud rate 115200
[10:26:01]ESP-ROM:esp32s3-20210327
[10:26:01]Build:Mar 27 2021
[10:26:01]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[10:26:01]Saved PC:0x400454d5
[10:26:01]SPIWP:0xee
[10:26:01]mode:QIO, clock div:1
[10:26:01]load:0x3fce3808,len:0x164c
[10:26:01]ets_loader.c 78
[10:26:02]ESP-ROM:esp32s3-20210327
[10:26:02]Build:Mar 27 2021
[10:26:02]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[10:26:02]Saved PC:0x400454d5
[10:26:02]SPIWP:0xee
[10:26:02]mode:QIO, clock div:1
[10:26:02]load:0x3fce3808,len:0x164c
[10:26:02]ets_loader.c 78
[10:26:02]ESP-ROM:esp32s3-20210327
[10:26:02]Build:Mar 27 2021
[10:26:02]rst:0x10 (RTCWDT_RTC_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[10:26:02]SPIWP:0xee
[10:26:02]mode:QIO, clock div:1
[10:26:02]load:0x3fce3808,len:0x164c
[10:26:02]ets_loader.c 78
[10:26:04]ESP-ROM:esp32s3-20210327
[10:26:04]Build:Mar 27 2021
[10:26:04]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[10:26:04]Saved PC:0x400454d5
[10:26:04]SPIWP:0xee
[10:26:04]mode:QIO, clock div:1
[10:26:04]load:0x3fce3808,len:0x164c
[10:26:04]ets_loader.c 78
[10:26:05]ESP-ROM:esp32s3-20210327
[10:26:05]Build:Mar 27 2021
[10:26:05]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[10:26:05]Saved PC:0x400454d5
[10:26:05]SPIWP:0xee
[10:26:05]mode:QIO, clock div:1
[10:26:05]load:0x3fce3808,len:0x164c
[10:26:05]ets_loader.c 78
[10:26:05]ESP-ROM:esp32s3-20210327
[10:26:05]Build:Mar 27 2021
[10:26:05]rst:0x10 (RTCWDT_RTC_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[10:26:05]SPIWP:0xee
[10:26:05]mode:QIO, clock div:1
[10:26:05]load:0x3fce3808,len:0x164c
[10:26:05]ets_loader.c 78
```

this is my esp

[https://de.aliexpress.com/item/1005005024027877.html?spm=a2g0o.order_list.order_list_main.78.42485c5f9HblHm&gatewayAdapt=glo2deu](url)

**Reply by syssi** [reply]
Could you provide your full YAML configuration?

**Comment by riker65** [comment]
Hi

it should be just your example , only with another board.
thanks

```
substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  mac_address: C8:47:8C:E1:E2:E1
  # Defaults to "JK02". Please use "JK04" if you have some old JK-BMS version (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02_32S


#heltec integration

#esphome:
#  name: oled2
#  platform: ESP32
#   platform: ESP32-S3
#  board: heltec_wifi_kit_32(V3)
#  board: heltec_wifi_kit_32  

#  restore_from_flash: true
#  board:  esp32s3

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.4.0

esp32:
#  board: wemos_d1_mini32
#  platform: ESP32
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
 #https://github.com/esphome/issues/issues/3580     
      
external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
#api:

mqtt:
   broker: !secret mqtt_host
   username: !secret mqtt_username
   password: !secret mqtt_password
   id: mqtt_client

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name} retrieve settings"
    retrieve_device_info:
      name: "${name} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${name} balance trigger voltage"
    cell_count:
      name: "${name} cell count"
    total_battery_capacity:
      name: "${name} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    voltage_calibration:
      name: "${name} voltage calibration"
    current_calibration:
      name: "${name} current calibration"
    power_off_voltage:
      name: "${name} power off voltage"
    max_balance_current:
      name: "${name} max balance current"
    max_charge_current:
      name: "${name} max charge current"
    max_discharge_current:
      name: "${name} max discharge current"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    cell_voltage_17:
      name: "${name} cell voltage 17"
    cell_voltage_18:
      name: "${name} cell voltage 18"
    cell_voltage_19:
      name: "${name} cell voltage 19"
    cell_voltage_20:
      name: "${name} cell voltage 20"
    cell_voltage_21:
      name: "${name} cell voltage 21"
    cell_voltage_22:
      name: "${name} cell voltage 22"
    cell_voltage_23:
      name: "${name} cell voltage 23"
    cell_voltage_24:
      name: "${name} cell voltage 24"
    cell_resistance_1:
      name: "${name} cell resistance 1"
    cell_resistance_2:
      name: "${name} cell resistance 2"
    cell_resistance_3:
      name: "${name} cell resistance 3"
    cell_resistance_4:
      name: "${name} cell resistance 4"
    cell_resistance_5:
      name: "${name} cell resistance 5"
    cell_resistance_6:
      name: "${name} cell resistance 6"
    cell_resistance_7:
      name: "${name} cell resistance 7"
    cell_resistance_8:
      name: "${name} cell resistance 8"
    cell_resistance_9:
      name: "${name} cell resistance 9"
    cell_resistance_10:
      name: "${name} cell resistance 10"
    cell_resistance_11:
      name: "${name} cell resistance 11"
    cell_resistance_12:
      name: "${name} cell resistance 12"
    cell_resistance_13:
      name: "${name} cell resistance 13"
    cell_resistance_14:
      name: "${name} cell resistance 14"
    cell_resistance_15:
      name: "${name} cell resistance 15"
    cell_resistance_16:
      name: "${name} cell resistance 16"
    cell_resistance_17:
      name: "${name} cell resistance 17"
    cell_resistance_18:
      name: "${name} cell resistance 18"
    cell_resistance_19:
      name: "${name} cell resistance 19"
    cell_resistance_20:
      name: "${name} cell resistance 20"
    cell_resistance_21:
      name: "${name} cell resistance 21"
    cell_resistance_22:
      name: "${name} cell resistance 22"
    cell_resistance_23:
      name: "${name} cell resistance 23"
    cell_resistance_24:
      name: "${name} cell resistance 24"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    power_tube_temperature:
      name: "${name} power tube temperature"
    state_of_charge:
      name: "${name} state of charge"
    capacity_remaining:
      name: "${name} capacity remaining"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    total_runtime:
      name: "${name} total runtime"
    balancing_current:
      name: "${name} balancing current"
    errors_bitmask:
      name: "${name} errors bitmask"

switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "${name} errors"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
```

**Reply by syssi** [reply]
Is the board stable of you don't use this project / external component?

**Reply by syssi** [reply]
Please try to play around with the framework & platform versions:

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
```

```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: recommended
    platform_version: 4.4.0
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
```

**Reply by riker65** [reply]
will try thanks

**Reply by riker65** [reply]
> Is the board stable of you don't use this project / external component?

Yes, I only have it shortly and used in a smal demo but running stable and display is working. very simple project so 
do not have a lot experience with it

**Comment by riker65** [comment]
same result with first config.

thanks anyway.

kind of tricky

[13:37:07]rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[13:37:07]Saved PC:0x400454d5
[13:37:07]SPIWP:0xee
[13:37:07]mode:QIO, clock div:1
[13:37:07]load:0x3fce3808,len:0x164c
[13:37:07]ets_loader.c 78
[13:37:07]ESP-ROM:esp32s3-20210327
[13:37:07]Build:Mar 27 2021
[13:37:07]rst:0x10 (RTCWDT_RTC_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[13:37:07]SPIWP:0xee
[13:37:07]mode:QIO, clock div:1
[13:37:07]load:0x3fce3808,len:0x164c



2. also error with 
```
 PLATFORM: Espressif 32 (4.4.0) > Espressif ESP32-S3-DevKitC-1
HARDWARE: ESP32S3 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
**Error: This board doesn't support espidf framework!**
```

**Reply by syssi** [reply]
You could place your question here: https://github.com/esphome/issues

IMO it's independent of this external component / project.

**Comment by riker65** [comment]
thx will do, good to know that external components are not the root cause.

**Comment by riker65** [comment]
Hi, 
did find a solution but do not understand what is the difference
using platform esp32 instead of ESP32: .....esphome is still mystic to myself

using the board like this at least does start it and BLE and MQTT is running.

`esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.4.0
  platform: ESP32
  board: esp32-s3-devkitc-1
`


next step is to get the display running.

**Reply by syssi** [reply]
You have changed the framework to `arduino` by removing the `esp-idf` instruction. The ESP32 in capitals doesn't make a difference. :-)

**Comment by riker65** [comment]
I was referring to the ESP32: section.

this is now removed and using the platform statement.
no sure about the impact, that is why I did not want to start with esphome....now fighting with indents......old school :-)


```
esphome:
  name: ${name}
  comment: ${device_description}

  project:

    name: "syssi.esphome-jk-bms"

    version: 1.4.0

  platform: ESP32

  board: esp32-s3-devkitc-1
```

```

 # removed-commented out 
 #esp32:
 #  board: wemos_d1_mini32
 #  framework:
 #    type: esp-idf
#    version: latest
```

**Comment by riker65** [comment]
HJi
do you have an example how to transform the variable to print it.

in lamba:
`          it.printf(0, 30, id(font2), "1  %3.3f", id("${name} cell voltage 1").state.c_str());  `

`error: request for member 'state' in 'esphome::id<const char>(((const char*)"ht-jk-bms cell voltage 1"))', which is of non-class type 'const char'`

thanks a lot

**Reply by syssi** [reply]
It looks like you doesn't know an important detail about ESPHome: If you want to access specific components or sensors you have to assign an identifier first. For example if you want to access the state of the cell voltage 1 sensor to have to extend the sensor definition first:

```
# From

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    cell_voltage_1:
      name: "${name} cell voltage 1"
```

```
# To
sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    cell_voltage_1:
      name: "${name} cell voltage 1"
      id: cell_voltage_1
```

The sensor has the identifier `cell_voltage_1` now which can be accessed without pain:

```
...
it.printf(0, 30, id(font2), "1  %3.3f", id(cell_voltage_1).state); 
...
```
