### DISCUSSION TITLE
esphome-jk-bms with webserver

### DISCUSSION THREAD

**Discussion by pfeupfeu** [syssi/esphome-jk-bms#270] [Ideas]
Hello,
I would like to combine esphome-jk-bms with the web-server feature. Unfortunately the esp-idf framework does not offer this feature. So I tried to use :

```
external_components:
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
```
      
but I get the Error message "ERROR Unexpected exception while reading configuration:"
![image](https://user-images.githubusercontent.com/44723598/223191462-cf31039f-6e63-479e-90e5-103eab1620f3.png)

What I'm doing wrong?

**Comment by syssi** [comment]
You could try to use the `arduino` framework. If you have luck the initial issue (crash on the first received BLE notification) was fixed.

**Reply by syssi** [reply]
On my system (Debian Bullseye, python 3.9.2, virtualenv) this builds fine:

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Your build issue was mentioned here:

https://github.com/esphome/esphome/pull/3500#issuecomment-1441399027
https://github.com/esphome/esphome/pull/3500#issuecomment-1455838800

**Comment by pfeupfeu** [comment]
Thank you for your very fast answer!

If I use the esp-idf framework (without a web server), the software runs and I get an acceptable to poor connection to the WiFi.
If I use the arduino framework, the software runs but I get no connection or only a very poor connection to the WiFi.
The router is only 3m away.

Ok, no  crash on the first received BLE notification, but other problems. I'm using a AZDelivery LOLIN32 Lite Board, and 

`board: lolin32_lite`

So I have to try the other workarounds.

**Comment by pfeupfeu** [comment]
Success! It is working! 
I used the second workaround you mentioned:

> https://github.com/esphome/esphome/pull/3500#issuecomment-1455838800

And the WiFi and BLE performance is very good.

Thany you very much!

**Reply by riker65** [reply]
Hi, this comment 3500 is beyond my program knowledge.

How did you implement it? thanks

**Reply by syssi** [reply]
I've prepared a user friendly version. Just use this configuration example:

https://github.com/syssi/esphome-jk-bms/blob/add-webinterface/esp32-ble-example.yaml

Or extend your configuration YAML with the green lines:

https://github.com/syssi/esphome-jk-bms/pull/278/files#diff-6d19e7b8b7435fb5c57e1ad1b8498afa48c2073ed985bf1fc1d82f08eb2ded56

This is the UI:

![webif](https://user-images.githubusercontent.com/2735933/224830855-3324d9ed-e08b-4336-8b86-77c68137f9ce.png)

**Comment by riker65** [comment]
Hi, strangewise I have some issues compiling on one environment windows10 , running on ubuntu ..

Reinstalled esphome-jk-bms from git already.

Do not understand what is missing.

Maybe anyone is having an idea?
python 3.10 on windows 




`Compiling .pioenvs\jk-bms\src\esphome\components\web_server_idf\web_server_idf.o
Compiling .pioenvs\jk-bms\src\esphome\components\web_server_idf\web_server_idf_ota.o
src/esphome/components/web_server/web_server.cpp: In lambda function:
src/esphome/components/web_server/web_server.cpp:107:40: error: 'class esphome::Application' has no member named 'get_friendly_name'
                    root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();                                        ^~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:107:91: error: 'class esphome::Application' has no member named 'get_friendly_name'
                    root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();
                                                                                           ^~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:108:42: error: 'class esphome::Application' has no member named 'get_comment'; did you mean 'get_name'?
                    root["comment"] = App.get_comment();
                                          ^~~~~~~~~~~
                                          get_name
*** [.pioenvs\jk-bms\src\esphome\components\web_server\web_server.o] Error 1
=============================================================== [FAILED] Took 134.11 seconds ===================`

**Reply by syssi** [reply]
If you have the choice I would like to focus on ubuntu as build host. :-)

**Comment by riker65** [comment]
Hi, strangewise, even ota: is set, no ota options to select file on webgui ? 

what am I missing?

**Reply by syssi** [reply]
Please keep in mind you are using the ESPHome pull request: https://github.com/esphome/esphome/pull/3500

The description mentions:

> Known limitation:
>  - No OTA update support yet.

**Reply by syssi** [reply]
Please use the command line `esphome run yourconfig.yaml` to push OTA updates to your (`ota` enabled) devices.

**Reply by riker65** [reply]
yes via cli it is working, just wondering why webgui ota update is not available? 
thx

issue is when testing and changing the device name- ota is not working because not found in network , than uploading would be a good option

**Reply by riker65** [reply]
ok understood

**Comment by testpaul999** [comment]
Hi, 
I‘v use this with the actual esp32-ble and it works fine.
But, pls is it possible the sort the entry’s in the right order?
1,2,3,4,5,6,7 and not 1,10,11,….19,2,20,21….

regards

**Reply by syssi** [reply]
No. The order is hardcoded/auto-generated and cannot be changed/controlled at the moment.

**Reply by testpaul999** [reply]
👍🏻 thx 
And also the header at the name field?
Jk-bms-ble ….. „cell count“?
Regards

**Reply by syssi** [reply]
This is just a setting and can be easily adjusted:

```
number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "Ausloesespannung des Balancers"
    cell_count:
      name: "Zellanzahl"
    total_battery_capacity:
      name: "Nennkapazitaet"
```

**Reply by testpaul999** [reply]
Hallo,
Native Sprache ist deutlich einfacher. 😉
Mich „stört“ der Header. Ich der Text, ich hätte gerne nur den „cell count“ z.B.

danke

**Reply by syssi** [reply]
`${name}` is the variable which should be removed:

```
    cell_count:
      name: "${name} cell count"
```

to

```
    cell_count:
      name: "cell count"
```

**Reply by testpaul999** [reply]
Einfach $Name weglassen oder?

**Reply by testpaul999** [reply]
Danke 🙂

**Comment by andyw73** [comment]
I have been using the arduino framework however I am tryin tho incorperate the bluetooth to occupy the bms channel for safety reasons.
When trying to compile the firmware to use esp-idf and the above code from PopOs which is ubuntu based I get an error:
Compiling .pioenvs/aisite-access-demo/src/esphome/components/wifi/wifi_component.o
In file included from src/esphome/components/web_server/web_server.cpp:1:
src/esphome/components/web_server/web_server.h:17:53: error: expected initializer before 'PROGMEM'
 extern const uint8_t ESPHOME_WEBSERVER_INDEX_HTML[] PROGMEM;
                                                     ^~~~~~~
src/esphome/components/web_server/web_server.cpp: In member function 'void esphome::web_server::WebServer::handle_index_request(esphome::web_server_idf::AsyncWebServerRequest*)':
src/esphome/components/web_server/web_server.cpp:330:50: error: 'ESPHOME_WEBSERVER_INDEX_HTML' was not declared in this scope
       request->beginResponse_P(200, "text/html", ESPHOME_WEBSERVER_INDEX_HTML, ESPHOME_WEBSERVER_INDEX_HTML_SIZE);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:330:50: note: suggested alternative: 'ESPHOME_WEBSERVER_INDEX_HTML_SIZE'
       request->beginResponse_P(200, "text/html", ESPHOME_WEBSERVER_INDEX_HTML, ESPHOME_WEBSERVER_INDEX_HTML_SIZE);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ESPHOME_WEBSERVER_INDEX_HTML_SIZE
Has anyone else encountered this issue?

**Reply by syssi** [reply]
Could you provide your YAML and the used ESPHome version?

**Comment by andyw73** [comment]
The code responsible is below. I have not included the bluetooth tracker....

```
substitutions:
  name: aisite-access-demo
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17
  mac_address: C8:47:8C:E2:D7:A2

esphome:
  name: ${name}
  platformio_options:
    build_flags:
      - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.5.0

esp32:
  board: nodemcu-32s
  #variant: esp32
  framework:
    type: esp-idf
    #version: latest
    
ble_client:
  - mac_address: ${mac_address}
    id: client0

external_components:
  - source: ${external_components_source}
    refresh: 0s
    
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.25
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8
ota:

logger:
  level: WARN

# web configuration entry
web_server:
  local: false
  port: 80
  auth:
    username: #####
    password: #####

# api:

mqtt:
  broker: 192.168.1.153	

# rest of code.....
```

The esphome version is 2023.6.3 which is the lastest version.

**Reply by syssi** [reply]
If you just want to occupy the bluetooth module you could stick to the Arduino framework and the official `web_server` component:

```
substitutions:
  name: aisite-access-demo
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17
  mac_address: C8:47:8C:E2:D7:A2

esphome:
  name: ${name}
  platformio_options:
    build_flags:
      - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.5.0

esp32:
  board: nodemcu-32s
  #variant: esp32

ble_client:
  - mac_address: ${mac_address}
    id: client0

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.25
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

ota:

logger:
  level: WARN

# web configuration entry
web_server:
  local: false
  port: 80

# api:

mqtt:
  broker: 192.168.1.153

# rest of code.....
```
