### DISCUSSION TITLE
jk-bms, esp32, ttl value update interval

### DISCUSSION THREAD

**Discussion by harald7** [syssi/esphome-jk-bms#271] [General]
I have the esp32 connected via cable. Everything is fine and the values are displayed in iobroker.  The values are updated every 5s.
Is there are way to decrease the 5s?

Thanks a lot!
Harald

**Comment by syssi** [comment]
You can change the `update_interval`:

```
jk_modbus:
  id: modbus0
  uart_id: uart0
  rx_timeout: 50ms
  update_interval: 60s
```
