### DISCUSSION TITLE
ESPHOME v2023.3.0 error on compile

### DISCUSSION THREAD

**Discussion by twty** [syssi/esphome-jk-bms#289] [General]
Hi,
Any breaking change on esphome version 2023.3.0  affect esphome-jk-bms.
I have try to update and it fail.
I attach the log.
Have reverted to esp2023.2.4 and is working fine .
Homeassistant installed on RPI 4
Thanks
[logs_jk-bms60a_run.txt](https://github.com/syssi/esphome-jk-bms/files/11002776/logs_jk-bms60a_run.txt)

**Comment by syssi** [comment]
I've pushed a fix to `main`: https://github.com/syssi/esphome-jk-bms/pull/290/files

Please change the ESP-IDF platform version from `latest` to `recommended`:

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: recommended
```
