### DISCUSSION TITLE
Reboot if ESP loses connection -

### DISCUSSION THREAD

**Discussion by EasilyBoredEngineer** [syssi/esphome-jk-bms#296] [General]
Hi all, 

Just to let you know a way to reboot your esp if you have a crappy wifi AP and find that your esp periodically loses connection. 

At first I tried using the 'restart' platform set as a switch with an 'interval' automation set to every 15 minutes, but that put the esp in a reboot loop as interval is executed automatically at boot.

The solution is to use the time component - below is the relevant code block.

It basically tests every 2 minutes to see if your esp has a connection to home assistant, and if it doesn't it reboots. Seems to have made my system more solid - but, as I said, this isn't to address a problem with syssi's project (It's great!!) - it's just to address an issue I've found with my particular cheap wifi AP.

```
switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"
  - platform: restart
    name: "Esp Restart"
    id: esp_reset
    restore_mode: ALWAYS_OFF 
  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

#check connectivity and reboot

time:
  - platform: homeassistant
    on_time:
      - cron: '* /2 * * * *'
        then:
          if:
            condition:
              api.connected
            then:
            #nothing
            else:
              - switch.toggle: esp_reset
```
