### DISCUSSION TITLE
MQTT to Emonpi

### DISCUSSION THREAD

**Discussion by rosspeel** [syssi/esphome-jk-bms#300] [Ideas]
I have been using an Emonpi for a few years that allows me to send MQTT data to it, I am not verse well with ESP Home, Is there any way of instead of sending MQTT data to Home Assistant but to a Emonpi instead?

**Comment by syssi** [comment]
Please remove the `api:` line from your configuration and add

```
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
```

This will push messages to your MQTT broker.
