### DISCUSSION TITLE
Only one instance at mqtt possible?

### DISCUSSION THREAD

**Discussion by testpaul999** [syssi/esphome-jk-bms#345] [Q&A] [answered]
Hi,
Is it possible that only one instance appears in mqtt?
At the moment I see jk-bms and homeassistant.
I have the "API" deactivated and only mqtt active.
Thanks

**Comment by syssi** [comment, marked as answer]
`homeassistant` is the auto-discovery topic and can be disabled: 

```
mqtt:
  broker: ...
  username: ...
  password: ...
  discovery: false
```
