### DISCUSSION TITLE
Webinterface & MQTT without HA - maybe with ioBroker

### DISCUSSION THREAD

**Discussion by peff74** [syssi/esphome-jk-bms#367] [Q&A]
First of all, I would like to thank you for this ingenious project that gives us the possibility to read out the JK BMS properly.
I managed to get an ESP32 to read my BMS and send it via MQTT to my broker within a short time even without ESP Home & HA knowledge. 
Even the web server of the ESP works.
Brilliant!

Now I have a few questions to optimize my system if possible.
- there are topics sent via MQTT that I am not interested in, can I turn them off?
![2023-08-28 10_43_59-objects - ioBorker](https://github.com/syssi/esphome-jk-bms/assets/91614910/4e875792-2962-4364-8748-728bb036045e)

- is it possible to implement switches in the ioBroker, similar to the webinterface or HA? 

Thanks in advance

**Comment by syssi** [comment]
One of the topics (the `homeassistant` one) is used for auto-discovery. This can be disabled:

```
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
  discovery: false
```

The `esphome` and `info` topic is new to me. Could you provide some example messages published on this topic?

I have no experience with ioBroker and cannot help here.
