### DISCUSSION TITLE
Connect to BMS using Bluetooth UART

### DISCUSSION THREAD

**Discussion by 23900** [syssi/esphome-jk-bms#412] [Q&A]
I'm trying to connect to BMS directly with BLE UART.

```
                UART-TTL
┌──────────┐                ┌─────────────┐                ┌──────────┐
│          │<----- RX ------│tx1       rx2│<----- RX ------│          │
│  JK-BMS  │------ TX ----->│rx1 ESP32 tx2│------ TX ----->│ JK-BMS   │
│          │<----BLE_EN ----│             │<----BLE_STA----│ Bluetooth│
│          │------ 3.3v---->│             │------ 3.3v---->│ module   │
│          │<----- GND ---->│             │<----- GND----->│          │
│          │                │             │                │          │
└──────────┘                └─────────────┘                └──────────┘


```

Use ESP32 to bridge two uarts.

https://github.com/ssieb/esphome_components/tree/master/components/uart_mitm

```
  ble_sta_pin: GPIO15
  ble_en_pin: GPIO2

  rx_pin_uart_0: GPIO3
  tx_pin_uart_0: GPIO1
  rx_pin_uart_1: GPIO4 #mcu tx
  tx_pin_uart_1: GPIO15 #mcu rx
  rx_pin_uart_2: GPIO2 #ble tx > rx
  tx_pin_uart_2: GPIO17 #ble rx < tx


uart:
  - id: uart_1
    baud_rate: 115200
    #rx_buffer_size: 384
    tx_pin: ${tx_pin_uart_1}
    rx_pin: ${rx_pin_uart_1}

  - id: uart_2
    baud_rate: 115200
    #stop_bits: 1
    #rx_buffer_size: 384
    tx_pin: ${tx_pin_uart_2}
    rx_pin: ${rx_pin_uart_2}


uart_mitm:
  uart1: uart_1
  uart2: uart_2

binary_sensor:
  - platform: gpio
    name: "Bluetooth STA"
    pin: ${ble_sta_pin}
    id: ble_sta
  #Manually enable BLE_EN,
   # on_press:
   #   then:
   #     - switch.turn_on: ble_en
    on_release:
      then:
        - switch.turn_off: ble_en

switch:
  - platform: gpio
    name: "Bluetooth enabled"
    pin: ${ble_en_pin}
    id: ble_en
```

Hi @syssi  , do you happen to have a code branch that incorporates UART and BLE protocols?
Apologies for my English proficiency.

![JK-BMS-ESP32-Debug](https://github.com/syssi/esphome-jk-bms/assets/50922729/610905d0-8cf5-4f38-8923-f58002bf3770)
