### DISCUSSION TITLE
Would it be possible to integrate a heating control function?

### DISCUSSION THREAD

**Discussion by peff74** [syssi/esphome-jk-bms#473] [Q&A] [answered]
Hi,

I use a JK-BD4A17S4P.
The monitoring works wonderfully!

I have installed a small 30W heating mat for the cold season.
Until now, I control it via a separate thermostat. 

As the temperature data is already in the ESP, would it be possible to connect a relay module there and use it to control the mat?
Unfortunately, I am a layman in ESP Home I'm only on Arduino.
Can someone perhaps give me a few points of reference that I could try to use as a guide?

Br
Peff

**Comment by syssi** [comment]
This is an example how the setup / YAML could look like:

```
esphome:
  name: greenhouse-heating

esp8266:
  board: sonoff_th

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
api:
ota:
logger:  

i2c:
  - id: i2c_bus
    sda: GPIO4
    scl: GPIO14
    scan: true

sensor:
  - platform: bme280
    temperature:
      id: my_temperature
      name: "${name} temperature"
      oversampling: 16x
    pressure:
      name: "${name} pressure"
    humidity:
      name: "${name} humidity"
    address: 0x76
    update_interval: 60s

climate:
  - platform: thermostat
    name: "${name} mat"
    sensor: my_temperature
    heat_overrun: 1 °C
    min_idle_time: 180s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    heat_action:
      - switch.turn_on: relay
    idle_action:
      - switch.turn_off: relay
    visual:
      min_temperature: 0 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C
    preset:
      - name: "Lower bound"
        default_target_temperature_low: 0.0

switch:
  - platform: gpio
    name: "${name} relay"
    id: relay
    pin: GPIO12
```

**Comment by peff74** [comment, marked as answer]
would that be correct?
While we are at it, is the integration of the WT32-eth01 correct? 
I have found some contradictory information

THANX!!!

```
substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  # Akku gross
  mac_address: 20:22:09:27:7c:44
  # Akku klein
  # mac_address: 20:22:08:25:0f:a9
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02_32S

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

web_server:
  local: false
  
  
#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

ota:
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
# api:

mqtt:
   broker: !secret mqtt_host
   username: !secret mqtt_username
   password: !secret mqtt_password
   id: mqtt_client
   discovery: false

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("JK-", 0) == 0 || x.get_name().rfind("JK_", 0) == 0) {
            ESP_LOGI("ble_adv", "New JK-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    heating:
      name: "${name} heating"
    online_status:
      name: "${name} online status"

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name} retrieve settings"
    retrieve_device_info:
      name: "${name} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${name} balance trigger voltage"
    cell_count:
      name: "${name} cell count"
    total_battery_capacity:
      name: "${name} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    voltage_calibration:
      name: "${name} voltage calibration"
    current_calibration:
      name: "${name} current calibration"
    power_off_voltage:
      name: "${name} power off voltage"
    max_balance_current:
      name: "${name} max balance current"
    max_charge_current:
      name: "${name} max charge current"
    max_discharge_current:
      name: "${name} max discharge current"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 01"
    cell_voltage_2:
      name: "${name} cell voltage 02"
    cell_voltage_3:
      name: "${name} cell voltage 03"
    cell_voltage_4:
      name: "${name} cell voltage 04"
    cell_voltage_5:
      name: "${name} cell voltage 05"
    cell_voltage_6:
      name: "${name} cell voltage 06"
    cell_voltage_7:
      name: "${name} cell voltage 07"
    cell_voltage_8:
      name: "${name} cell voltage 08"
    cell_voltage_9:
      name: "${name} cell voltage 09"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_resistance_1:
      name: "${name} cell resistance 01"
    cell_resistance_2:
      name: "${name} cell resistance 02"
    cell_resistance_3:
      name: "${name} cell resistance 03"
    cell_resistance_4:
      name: "${name} cell resistance 04"
    cell_resistance_5:
      name: "${name} cell resistance 05"
    cell_resistance_6:
      name: "${name} cell resistance 06"
    cell_resistance_7:
      name: "${name} cell resistance 07"
    cell_resistance_8:
      name: "${name} cell resistance 08"
    cell_resistance_9:
      name: "${name} cell resistance 09"
    cell_resistance_10:
      name: "${name} cell resistance 10"
    cell_resistance_11:
      name: "${name} cell resistance 11"
    cell_resistance_12:
      name: "${name} cell resistance 12"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    heating_current:
      name: "${name} heating current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
      id: temp_sensor_1
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    # temperature_sensor_3:
    #   name: "${name} temperature sensor 3"
    # temperature_sensor_4:
    #   name: "${name} temperature sensor 4"
    power_tube_temperature:
      name: "${name} power tube temperature"
    state_of_charge:
      name: "${name} state of charge"
    capacity_remaining:
      name: "${name} capacity remaining"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    total_runtime:
      name: "${name} total runtime"
    balancing_current:
      name: "${name} balancing current"
    errors_bitmask:
      name: "${name} errors bitmask"

climate:
  - platform: thermostat
    name: "${name} mat"
    sensor: temp_sensor_1
    heat_overrun: 1 °C
    min_idle_time: 180s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    heat_action:
      - switch.turn_on: heater
    idle_action:
      - switch.turn_off: heater
    visual:
      min_temperature: 0 °C
      max_temperature: 35 °C
      temperature_step: 0.5 °C  
    default_preset: Lower bound
    preset:
      - name: Lower bound
        default_target_temperature_low: 6 °C



switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${name} enable bluetooth connection"
    
  - platform: gpio
    name: "${name} heater"
    pin: GPIO14
    id: heater

text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "${name} errors"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
```
