### DISCUSSION TITLE
Invert number of discharging power

### DISCUSSION THREAD

**Discussion by MStapelfeldt** [syssi/esphome-jk-bms#497] [Q&A] [answered]
Hi there, I'm working on my dashboard card for the bms and have 2 conditional cards:
```
      - type: conditional
        conditions:
          - condition: numeric_state
            entity: sensor.jk_bms_charging_power
            above: 0
        card:
          type: gauge
          entity: sensor.jk_bms_charging_power
          needle: true
          min: -100
          max: 100
          segments:
            - from: -100
              color: var(--error-color)
            - from: -75
              color: var(--warning-color)
            - from: -50
              color: var(--success-color)
            - from: 50
              color: var(--warning-color)
            - from: 75
              color: var(--error-color)
      - type: conditional
        conditions:
          - condition: numeric_state
            entity: sensor.jk_bms_discharging_power
            above: 0
        card:
          type: gauge
          entity: sensor.jk_bms_discharging_power
          needle: true
          min: -100
          max: 100
          segments:
            - from: -100
              color: var(--error-color)
            - from: -75
              color: var(--warning-color)
            - from: -50
              color: var(--success-color)
            - from: 50
              color: var(--warning-color)
            - from: 75
              color: var(--error-color)
```
0W should show the needle in the middle, charging positive range and discharging negativ. For this I need to invert the `sensor.jk_bms_discharging_power` and struggle to do so. Could anybody point me into the right direction?

Thank you

**Comment by syssi** [comment, marked as answer]
Add a `filter` and `multiply` the measurement by `-1.0`:

```
sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    discharging_power:
      name: "${name} discharging power"
      filters:
        - multiply: -1.0
```

**Reply by MStapelfeldt** [reply]
That was to easy 😅 thanks a lot
![Screenshot_2024-04-30-10-56-19-143_io homeassistant companion android-edit](https://github.com/syssi/esphome-jk-bms/assets/6480145/71233b91-fb81-4190-80a4-0aa6594b7de5)

**Comment by syssi** [comment]
I would be happy about a screenshot of your dashboard/card!

**Reply by MStapelfeldt** [reply]
ok, sry but one more stupid question. :D I've added
```

  - platform: total_daily_energy
    name: "bms0 charging energy today"
    icon: mdi:counter
    power_id: bms0_charging_power
    accuracy_decimals: 3
    unit_of_measurement: kWh
    restore: true
    filters:
      - multiply: 0.001

  - platform: total_daily_energy
    name: "bms0 discharging energy today"
    icon: mdi:counter
    power_id: bms0_discharging_power
    accuracy_decimals: 3
    unit_of_measurement: kWh
    restore: true
    filters:
      - multiply: 0.001
```
For Energy Dashboard, so I need positiv and negativ discharging values. Any idea?

Regarding the screenshot: I've added it at the moment only in my total overview. for all enery sensors, but when I add it to a solar dashboard (Epever Tracer and JK BMS) I'll share with you!

**Reply by syssi** [reply]
You need two different sensor entities:

```
sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    discharging_power:
      name: "${name} discharging power"
      id: bms0_discharging_power
      on_value:
        then:
          - sensor.template.publish:
            id: bms0_discharging_power_negative
            state: !lambda 'return -1.0f * x;'

  - platform: template
    name: "bms0 discharging power negative"
    update_interval: never
    id: bms0_discharging_power_negative
```

On each sensor update of the `bms0_discharging_power` sensor the measurement will be passed inverted to the template sensor called `bms0_discharging_power_negative`.
