### DISCUSSION TITLE
prevent sending homeassistant topics

### DISCUSSION THREAD

**Discussion by holle75** [syssi/esphome-jk-bms#530] [General]
Hi, is there any way to prevent sending of the homeassistant topics when the ESP is started?
 for example 
homeassistant/sensor/jk-bms/jk-bms_cell_voltage_4

i only use 
jk_bms_2462abc9d910:jk-bms/sensor/jk-bms_cell_voltage_4/state:.* cell_voltage_4

in my mqtt server and the doubled topics just create more traffic.

**Comment by syssi** [comment]
Yes. These topics are used for auto-discovery of the device using Home Assistant. If you don't need the auto-discovery you can turn it off:

```
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
  discovery: false
```

See https://esphome.io/components/mqtt.html
