### DISCUSSION TITLE
Balancer switch

### DISCUSSION THREAD

**Discussion by jopl** [syssi/esphome-jk-bms#587] [Q&A]
Dear all,
I have got ESP8266 connected to the JK-BMS.
Both of the switches "Charging" and "Discharging" are working well - based on yaml code below (based on example).
But neither "balancing" nor "balancer" are switches :-o.
Does exist a switch for balancer, please? I can see it on github pages ... therefore most probably it is possible ...
Regards, Josef.

Not working ... errors "[balancing] is an invalid option for [switch.jk_bms]. Please check the indentation." and "[balancer] is an invalid option for [switch.jk_bms]. Please check the indentation." appear.

```
switch:
  - platform: jk_bms
    charging:
      name: "Charging - ${friendly_name}"
    discharging:
      name: "Discharging- ${friendly_name}"
    balancing:
       name: "Balancer- ${friendly_name}"
    balancer:
       name: "Balancer- ${friendly_name}"
```
