### DISCUSSION TITLE
Min and Max cell voltages over UART esp8266

### DISCUSSION THREAD

**Discussion by alanv72** [syssi/esphome-jk-bms#627] [General]
Looks like it is a limitation of UART, but asking for confirmation.

Looking into modbus now...

**Comment by syssi** [comment]
The values gets calculated by the component and exposed here:

```
sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
```

Does this answer your question?
