### DISCUSSION TITLE
JK_B2A8S20P - ESP32 cannot connect to JK_BLE device once ESP32 gets restarted.

### DISCUSSION THREAD

**Discussion by janekbet** [syssi/esphome-jk-bms#635] [Q&A]
Hi,
I have problem with my JK B2A8S20P. My ESP32dev board is able to connect to JK BMS via BLE only once after flashing ESP32 board via USB.
After OTA software update esphome cannot connect to JK.
When I disconnect ESP32dev board from power supply and connect once again, esphome cannot connect to JK BMS.
SW and HW:
ESPHome  2024.11.3
JK HW Ver: V11A
JK SW Ver: V11.55

Any idea how to fix it?

In ESPHome logs I see such errors:
```
[21:02:15][I][esp32_ble_client:067]: [0] [xx:xx:xx:xx:xx:xx] 0x00 Attempting BLE connection
[21:02:15][D][esp-idf:000][BTU_TASK]: W (1057641) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
[21:02:15][D][esp-idf:000][BTU_TASK]: W (1058064) BT_APPL: gattc_conn_cb: if=4 st=0 id=4 rsn=0x3e
[21:02:15][D][esp32_ble_server:164]: BLE Client disconnected
[21:02:15][W][esp32_ble_client:143]: [0] [xx:xx:xx:xx:xx:xx] Connection failed, status=133
```

Here is my configuration yaml, that contains other sensors:
```
substitutions:
  name: esp32
  friendly_name: esp32-hymer
  mac_address: xx:xx:xx:xx:xx:xx
  protocol_version: JK02_32S
  name_battery: Battery

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble
  - source: github://syssi/esphome-jk-bms@main

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  logs:
    esp32_ble_tracker: INFO
    esp32_ble_client: INFO

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

esp32_ble_tracker:
  scan_parameters:
    active: false
i2c:
  sda: GPIO21
  scl: GPIO22

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

victron_ble:
  - id: MySmartSolar
    mac_address: xxxxxxxxxxxx
    bindkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

sensor:
  # MySmartSolar
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT Output Voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT Output Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT Yield Today"
    type: YIELD_TODAY
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT PV Power"
    type: PV_POWER
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT Load Current"
    type: LOAD_CURRENT

  - platform: mpu6050
    address: 0x68
    update_interval: 200ms
    accel_x:
      name: "MPU6050 Accel X"
    accel_y:
      name: "MPU6050 Accel Y"

  - platform: qmc5883l
    address: 0x0D
    heading:
      name: "QMC5883L Heading"
    temperature:
      name: "QMC5883L Temperature"
      filters:
        - offset: 34.0
    range: 200uT
    oversampling: 512x
    update_interval: 1s

  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name_battery} min cell voltage"
    max_cell_voltage:
      name: "${name_battery} max cell voltage"
    min_voltage_cell:
      name: "${name_battery} min voltage cell"
    max_voltage_cell:
      name: "${name_battery} max voltage cell"
    delta_cell_voltage:
      name: "${name_battery} delta cell voltage"
    average_cell_voltage:
      name: "${name_battery} average cell voltage"
    cell_voltage_1:
      name: "${name_battery} cell voltage 1"
    cell_voltage_2:
      name: "${name_battery} cell voltage 2"
    cell_voltage_3:
      name: "${name_battery} cell voltage 3"
    cell_voltage_4:
      name: "${name_battery} cell voltage 4"

    cell_resistance_1:
      name: "${name_battery} cell resistance 1"
    cell_resistance_2:
      name: "${name_battery} cell resistance 2"
    cell_resistance_3:
      name: "${name_battery} cell resistance 3"
    cell_resistance_4:
      name: "${name_battery} cell resistance 4"

    total_voltage:
      name: "${name_battery} total voltage"
    current:
      name: "${name_battery} current"
    heating_current:
      name: "${name_battery} heating current"
    power:
      name: "${name_battery} power"
    charging_power:
      name: "${name_battery} charging power"
    discharging_power:
      name: "${name_battery} discharging power"
    temperature_sensor_1:
      name: "${name_battery} temperature sensor 1"
    temperature_sensor_2:
      name: "${name_battery} temperature sensor 2"
    # temperature_sensor_3:
    #   name: "${name_battery} temperature sensor 3"
    # temperature_sensor_4:
    #   name: "${name_battery} temperature sensor 4"
    power_tube_temperature:
      name: "${name_battery} power tube temperature"
    balancing:
      name: "${name_battery} balancing"
    state_of_charge:
      name: "${name_battery} state of charge"
    capacity_remaining:
      name: "${name_battery} capacity remaining"
    total_battery_capacity_setting:
      name: "${name_battery} total battery capacity setting"
    charging_cycles:
      name: "${name_battery} charging cycles"
    total_charging_cycle_capacity:
      name: "${name_battery} total charging cycle capacity"
    total_runtime:
      name: "${name_battery} total runtime"
    balancing_current:
      name: "${name_battery} balancing current"
    errors_bitmask:
      name: "${name_battery} errors bitmask"

binary_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT is in Fault state"
    type: DEVICE_STATE_FAULT
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT has Error"
    type: CHARGER_ERROR

  - platform: jk_bms_ble
    balancing:
      name: "${name_battery} balancing"
    charging:
      name: "${name_battery} charging"
    discharging:
      name: "${name_battery} discharging"
    heating:
      name: "${name_battery} heating"
    online_status:
      name: "${name_battery} online status"

text_sensor:
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: MySmartSolar
    name: "MPPT Error reason"
    type: CHARGER_ERROR

  - platform: jk_bms_ble
    errors:
      name: "${name_battery} errors"
    total_runtime_formatted:
      name: "${name_battery} total runtime formatted"

button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name_battery} retrieve settings"
    retrieve_device_info:
      name: "${name_battery} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${name_battery} balance trigger voltage"
    cell_count:
      name: "${name_battery} cell count"
    total_battery_capacity:
      name: "${name_battery} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name_battery} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name_battery} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name_battery} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name_battery} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name_battery} balance starting voltage"
    voltage_calibration:
      name: "${name_battery} voltage calibration"
    current_calibration:
      name: "${name_battery} current calibration"
    power_off_voltage:
      name: "${name_battery} power off voltage"
    max_balance_current:
      name: "${name_battery} max balance current"
    max_charge_current:
      name: "${name_battery} max charge current"
    max_discharge_current:
      name: "${name_battery} max discharge current"
    charge_overcurrent_protection_delay:
      name: "${name_battery} charge overcurrent protection delay"
    charge_overcurrent_protection_recovery_time:
      name: "${name_battery} charge overcurrent protection recovery time"
    discharge_overcurrent_protection_delay:
      name: "${name_battery} discharge overcurrent protection delay"
    discharge_overcurrent_protection_recovery_time:
      name: "${name_battery} discharge overcurrent protection recovery time"
    short_circuit_protection_delay:
      name: "${name_battery} short circuit protection delay"
    short_circuit_protection_recovery_time:
      name: "${name_battery} short circuit protection recovery time"
    charge_overtemperature_protection:
      name: "${name_battery} charge overtemperature protection"
    charge_overtemperature_protection_recovery:
      name: "${name_battery} charge overtemperature protection recovery"
    discharge_overtemperature_protection:
      name: "${name_battery} discharge overtemperature protection"
    discharge_overtemperature_protection_recovery:
      name: "${name_battery} discharge overtemperature protection recovery"
    charge_undertemperature_protection:
      name: "${name_battery} charge undertemperature protection"
    charge_undertemperature_protection_recovery:
      name: "${name_battery} charge undertemperature protection recovery"
    power_tube_overtemperature_protection:
      name: "${name_battery} power tube overtemperature protection"
    power_tube_overtemperature_protection_recovery:
      name: "${name_battery} power tube overtemperature protection recovery"

switch:
  - platform: jk_bms_ble
    charging:
      name: "${name_battery} charging"
    discharging:
      name: "${name_battery} discharging"
    balancer:
      name: "${name_battery} balancer"
    heating:
      name: "${name_battery} heating"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${name_battery} enable bluetooth connection"
```
