### DISCUSSION TITLE
"delta filter" on binary sensor

### DISCUSSION THREAD

**Discussion by holle75** [syssi/esphome-jk-bms#703] [Q&A]
pulling my hair for hours .... i want to only send the status of a binary sensor when state has changed.
on sensors i can achieve this with a delta filter (fe voltage change min 0.01).

How can i achieve this with a binary sensor who publish ON/OFF? Can´t find any reference (i understand) on the net.

And another question it seems i´m not able to find an answer: how to define a global filter (if exist)? Meaning ONE filter for all sensors or all binary sensors? Or do i have to define a filter for each of them?

**Comment by syssi** [comment]
Do you use a native `api` connection or `mqtt`?

**Comment by holle75** [comment]
mqtt and my (maybe silly) goal is to reduce traffic

**Reply by syssi** [reply]
1. IMO the MQTT component publishes new messages only if the state has changed. This applies to normal sensors and binary sensors. A delta filter isn't supported but woulnd't change the traffic amount nevertheless
2. You have to apply a filter per sensor. ESPHome doesn't support global filters.

**Comment by holle75** [comment]
1) in my case all sensors (and debug) are published every 5 (definition) seconds to the mqtt server whether they are changed or not. But yes, you are right (i just realized now checking your info) the binary sensors are not. Ok, i need to modify my initial question: is there any easy way to make also the sensors behave as you described (publish only when state changes)? What would be a filter "send only when state is changed"?

**Reply by syssi** [reply]
Using a `delta` filter per sensor is the correct approach here:

```
sensor:
  - platform: template
    name: "Template Sensor"
    lambda: |-
      return 42.0;
    update_interval: 1s
    filters:
      - delta: 0.01
```

**Comment by holle75** [comment]
Good morning! Could you elaborate a bit?

What is lambda doing in your example? How to implement this filter on certain sensors that give back broader values (fe min_voltage_cell gives back the number of the cell, not a voltage)?

example sensors from the yaml:

    cell_voltage_3:
      name: "${name} cell voltage 3"
    balancing:
      name: "${name} balancing"
    state_of_charge:
      name: "${name} state of charge"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_cell_voltage:
      name: "${name} max cell voltage"

**Reply by syssi** [reply]
Ignore the template sensor and the lambda. It's just an example. This is what you are looking for:

```
cell_voltage_3:
  name: "${name} cell voltage 3"
  filters:
    - delta: 0.01
balancing:
  name: "${name} balancing"
  filters:
    - delta: 0.01
state_of_charge:
  name: "${name} state of charge"
  filters:
    - delta: 0.01
min_voltage_cell:
  name: "${name} min voltage cell"
  filters:
    - delta: 0.01
max_cell_voltage:
  name: "${name} max cell voltage"
  filters:
    - delta: 0.01
```

**Comment by holle75** [comment]
Thank you, appreciated.

**Reply by syssi** [reply]
Thanks for your flowers at the Akkudoktor thread!

**Comment by holle75** [comment]
sure. The least i can do. Really appreciate your time and work on this project. Kind of essential to use a JK-BMS or any other BMS when you want to monitor your solar plant or integrate it into your homeautomation system. People should be aware what those projects mean to all of us.

And for others because i just spent the time on the yaml (only the sensor part, be aware of the commented #### part):

part one
```
sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name} min cell voltage"
      filters:
	- delta: 0.01
    max_cell_voltage:
      name: "${name} max cell voltage"
      filters:
	- delta: 0.01
    min_voltage_cell:
      name: "${name} min voltage cell"
      filters:
	- delta: 0.01
    max_voltage_cell:
      name: "${name} max voltage cell"
      filters:
	- delta: 0.01
    delta_cell_voltage:
      name: "${name} delta cell voltage"
      filters:
	- delta: 0.01
    average_cell_voltage:
      name: "${name} average cell voltage"
      filters:
	- delta: 0.01
    cell_voltage_1:
      name: "${name} cell voltage 1"
      filters:
	- delta: 0.01
    cell_voltage_2:
      name: "${name} cell voltage 2"
      filters:
	- delta: 0.01
    cell_voltage_3:
      name: "${name} cell voltage 3"
      filters:
	- delta: 0.01
    cell_voltage_4:
      name: "${name} cell voltage 4"
      filters:
	- delta: 0.01
    cell_voltage_5:
      name: "${name} cell voltage 5"
      filters:
	- delta: 0.01
    cell_voltage_6:
      name: "${name} cell voltage 6"
      filters:
	- delta: 0.01
    cell_voltage_7:
      name: "${name} cell voltage 7"
      filters:
	- delta: 0.01
    cell_voltage_8:
      name: "${name} cell voltage 8"
      filters:
	- delta: 0.01
```
#### this part is eliminated in my case (only 8 cells and the resistances are not of my concern)

    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
     name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    cell_voltage_17:
      name: "${name} cell voltage 17"
    cell_voltage_18:
      name: "${name} cell voltage 18"
    cell_voltage_19:
      name: "${name} cell voltage 19"
    cell_voltage_20:
      name: "${name} cell voltage 20"
    cell_voltage_21:
      name: "${name} cell voltage 21"
    cell_voltage_22:
      name: "${name} cell voltage 22"
    cell_voltage_23:
      name: "${name} cell voltage 23"
    cell_voltage_24:
      name: "${name} cell voltage 24"
    cell_resistance_1:
      name: "${name} cell resistance 1"
    cell_resistance_2:
      name: "${name} cell resistance 2"
    cell_resistance_3:
      name: "${name} cell resistance 3"
    cell_resistance_4:
      name: "${name} cell resistance 4"
    cell_resistance_5:
      name: "${name} cell resistance 5"
    cell_resistance_6:
      name: "${name} cell resistance 6"
    cell_resistance_7:
      name: "${name} cell resistance 7"
    cell_resistance_8:
      name: "${name} cell resistance 8"
    cell_resistance_9:
      name: "${name} cell resistance 9"
    cell_resistance_10:
      name: "${name} cell resistance 10"
    cell_resistance_11:
      name: "${name} cell resistance 11"
    cell_resistance_12:
      name: "${name} cell resistance 12"
    cell_resistance_13:
      name: "${name} cell resistance 13"
    cell_resistance_14:
      name: "${name} cell resistance 14"
    cell_resistance_15:
      name: "${name} cell resistance 15"
    cell_resistance_16:
      name: "${name} cell resistance 16"
    cell_resistance_17:
      name: "${name} cell resistance 17"
    cell_resistance_18:
      name: "${name} cell resistance 18"
    cell_resistance_19:
      name: "${name} cell resistance 19"
    cell_resistance_20:
      name: "${name} cell resistance 20"
    cell_resistance_21:
      name: "${name} cell resistance 21"
    cell_resistance_22:
      name: "${name} cell resistance 22"
    cell_resistance_23:
      name: "${name} cell resistance 23"
    cell_resistance_24:
      name: "${name} cell resistance 24"
  
part two 
```
   total_voltage:
      name: "${name} total voltage"
      filters:
	- delta: 0.01
    current:
      name: "${name} current"
      filters:
	 - delta: 1.0
    heating_current:
      name: "${name} heating current"
      filters:
	- delta: 0.1
    power:
      name: "${name} power"
      filters:
	- delta: 1.0
    charging_power:
      name: "${name} charging power"
      filters:
	- delta: 1.0
    discharging_power:
      name: "${name} discharging power"
      filters:
	- delta: 1.0
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
      filters:
	- delta: 0.1
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
      filters:
	- delta: 0.1
    temperature_sensor_3:
      name: "${name} temperature sensor 3"
      filters:
	- delta: 0.1
    temperature_sensor_4:
      name: "${name} temperature sensor 4"
      filters:
	- delta: 0.1
    temperature_sensor_5:
      name: "${name} temperature sensor 5"
      filters:
	- delta: 0.1
    power_tube_temperature:
      name: "${name} power tube temperature"
      filters:
	- delta: 0.1
    balancing:
      name: "${name} balancing"
      filters:
	- delta: 0.1
    state_of_charge:
      name: "${name} state of charge"
      filters:
	- delta: 0.1
    capacity_remaining:
      name: "${name} capacity remaining"
      filters:
	- delta: 0.1
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
      filters:
	- delta: 0.1
    charging_cycles:
      name: "${name} charging cycles"
      filters:
	- delta: 0.1
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
      filters:
	- delta: 0.1
    total_runtime:
      name: "${name} total runtime"
      filters:
	- delta: 1.0
    balancing_current:
      name: "${name} balancing current"
      filters:
	- delta: 1.0
    errors_bitmask:
      name: "${name} errors bitmask"
      filters:
	- delta: 1.0
    emergency_time_countdown:
      name: "${name} emergency time countdown"
      filters:
	- delta: 1.0
```

**Comment by holle75** [comment]
This cut the amount of messages to ~1/10 (and CPU usage of the old rpi from 10 to 5%). Nice.

Any ideas for:

```
text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "${name} errors"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
```

and

the constant debug messages (or how to switch them off completely maybe)
