### DISCUSSION TITLE
For the inverter BMS with the FW >15.35  new parameter

### DISCUSSION THREAD

**Discussion by testpaul999** [syssi/esphome-jk-bms#708] [Ideas]
Hello,
Within the newer firmware >15.35 oder 14.26 they are new parameter to show.
![IMG_7295](https://github.com/user-attachments/assets/0ed7aaa0-25eb-4024-a19e-91802447b10e)
Is it possible to implement this pls also fore Bluetooth.

regards

**Comment by syssi** [comment]
Sure! Could you create a new issue and provide a `VERY_VERBOSE` ESPHome log + the expected measurements from the Android app ("210s" / "absorption"). May be we are able to identify the position of the new measurements at the `cell info frame`.

**Reply by testpaul999** [reply]
🤗 great 
The log with very_verbose is not the problem.
But I don’t have any android phone sorry is there one other way to capture this?

**Reply by syssi** [reply]
Yes. Just take another screenshot like the one above. It's just important to have a reference value to have an idea what we are looking for exactly.

**Reply by testpaul999** [reply]
:-( not so easy.
I‘v set all this parameter
logger:
  level: DEBUG
  logs:
    esp32_ble_tracker: INFO
    esp32_ble_client: INFO
to very_verbose and my D1_mini will ever appear at HA to see the log file.
Witch one of this I need?
And one more if I have a BT connection with the ESP32 I can’t connect the app as well. :-(
The only way can be the PC program to capture this. I‘ll try, but next weekend we go to short vacation.
Regards

**Reply by syssi** [reply]
```
logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble_tracker: VERY_VERBOSE
    jk_bms_ble: VERY_VERBOSE
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```

The log must be from a BLE connection. A log from a UART-TTL connection wont help.
