### DISCUSSION TITLE
JK Inverter BMS V19 is available now

### DISCUSSION THREAD

**Discussion by MBRetrofit** [syssi/esphome-jk-bms#747] [General]
[S105092df69f343459eea7a1e4a08d08eq.pdf](https://github.com/user-attachments/files/20453354/S105092df69f343459eea7a1e4a08d08eq.pdf)
![V19 all](https://github.com/user-attachments/assets/bd2f8818-a889-4283-ad3e-861bc3751760)
https://www.youtube.com/watch?v=dm_J_rrZzWI

Anyone tested? It may be similar?

**Comment by MBRetrofit** [comment]
[Sc2a24fca54534267a3b56c6f098af838s.pdf](https://github.com/user-attachments/files/20509552/Sc2a24fca54534267a3b56c6f098af838s.pdf)


This is the Display

**Comment by testpaul999** [comment]
Hi, 
i'v test the v19 bms and it looks good.
here are the actual log-file
16:34:00 press retrieve settings
16:34:15 press retrieve device info
[logs_jk-bms-ble-v19-debug-new_logs Kopie.txt](https://github.com/user-attachments/files/20534130/logs_jk-bms-ble-v19-debug-new_logs.Kopie.txt)

regrads

**Reply by MBRetrofit** [reply]
Did you connect over Bluetooth?

**Reply by testpaul999** [reply]
Yes I do.

**Reply by MBRetrofit** [reply]
That's bad.... how about connecting over RS485?

**Reply by syssi** [reply]
@testpaul999 Thanks for the ESPHome log / traffic capture. The size of the frames has increased slightly:

```
Cell info frame (version 3, 304 bytes) received
Settings frame (384 bytes) received
Device info frame (324 bytes) received
```

**Comment by Macrisu** [comment]
I have 5 HW19 BMS
HW 19 is not listed as supported on the main page of this project.

https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-example.yaml

Do I use "JK02_24S" for HW 19?

**Reply by syssi** [reply]
Please use this YAML as starting point and don't change the protocol:

https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-v15-example.yaml

It will be `JK02_32S`.

**Reply by Macrisu** [reply]
Well, I must be doing something wrong.


```
substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS v15 via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  mac_address: C8:47:80:37:6E:EA
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02_32S

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.1.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

```

```
2025-06-21 20:57:22.855 WARNING (MainThread) [homeassistant.components.esphome.manager] jk-bms: [W][jk_bms_ble:254]: [C8:47:80:37:6E:EA] Not connected
2025-06-21 20:57:27.859 WARNING (MainThread) [homeassistant.components.esphome.manager] jk-bms: [W][jk_bms_ble:254]: [C8:47:80:37:6E:EA] Not connected
2025-06-21 20:57:32.855 WARNING (MainThread) [homeassistant.components.esphome.manager] jk-bms: [W][jk_bms_ble:254]: [C8:47:80:37:6E:EA] Not connected
2025-06-21 20:57:37.857 WARNING (MainThread) [homeassistant.components.esphome.manager] jk-bms: [W][jk_bms_ble:254]: [C8:47:80:37:6E:EA] Not 
```
![bat1](https://github.com/user-attachments/assets/5cf5849f-bd4a-400a-9b54-3f29d51957a8)


The MAC is correct, as I use it it in Batmon configuration.
