### ISSUE TITLE
Second BMS still disconected after update

### ISSUE THREAD

**Issue by proasnet** [syssi/esphome-jk-bms#193]
Hello @syssi,
after some update esp-home, my second JKBMS was connected after a long random time, and disconected.
The first JKBMS working fine.
Both BMS are in the same place, the second periodically beeping ( as BT connecting ), and led still flashing.
Is connected so 10x daily for few seconds, and disconected.
Now, I am trying set longer time from 5s to 10s in setup, and is not possible Install to ESP, back to 5s is the same problem.
Instal from EPS Home become with error.

My setup:
```
substitutions:
  name: jk-bms
  bms0: "${name} bms0"
  bms1: "${name} bms1"
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  bms0_mac_address: C8:47:8C:E4:51:FA
  bms1_mac_address: C8:47:8C:E4:52:9D
  bms0_protocol_version: JK02
  bms1_protocol_version: JK02

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.2.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: DEBUG
  logs:
    jk_bms_ble: INFO

api:

esp32_ble_tracker:

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${bms0_protocol_version}
    throttle: 10s
    id: bms0
  - ble_client_id: client1
    protocol_version: ${bms1_protocol_version}
    throttle: 10s
    id: bms1

binary_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"

button:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    retrieve_settings:
      name: "${bms0} retrieve settings"
    retrieve_device_info:
      name: "${bms0} retrieve device info"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    retrieve_settings:
      name: "${bms1} retrieve settings"
    retrieve_device_info:
      name: "${bms1} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${bms0} balance trigger voltage"
    balance_starting_voltage:
      name: "${bms0} balance starting voltage"
    power_off_voltage:
      name: "${bms0} power off voltage"
    # ...

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    balance_trigger_voltage:
      name: "${bms1} balance trigger voltage"
    balance_starting_voltage:
      name: "${bms1} balance starting voltage"
    power_off_voltage:
      name: "${bms1} power off voltage"
    # ...

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    total_voltage:
      name: "${bms0} total voltage"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
    temperature_sensor_1:
      name: "${bms0} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0} temperature sensor 2"
    power_tube_temperature:
      name: "${bms0} power tube temperature"
    state_of_charge:
      name: "${bms0} state of charge"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    charging_cycles:
      name: "${bms0} charging cycles"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    cell_voltage_5:
      name: "${bms0} cell voltage 5"
    cell_voltage_6:
      name: "${bms0} cell voltage 6"
    cell_voltage_7:
      name: "${bms0} cell voltage 7"
    cell_voltage_8:
      name: "${bms0} cell voltage 8"
    # ...

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    total_voltage:
      name: "${bms1} total voltage"
    current:
      name: "${bms1} current"
    power:
      name: "${bms1} power"
    temperature_sensor_1:
      name: "${bms1} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms1} temperature sensor 2"
    power_tube_temperature:
      name: "${bms1} power tube temperature"
    state_of_charge:
      name: "${bms1} state of charge"
    capacity_remaining:
      name: "${bms1} capacity remaining"
    charging_cycles:
      name: "${bms1} charging cycles"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    cell_voltage_5:
      name: "${bms1} cell voltage 5"
    cell_voltage_6:
      name: "${bms1} cell voltage 6"
    cell_voltage_7:
      name: "${bms1} cell voltage 7"
    cell_voltage_8:
      name: "${bms1} cell voltage 8"
    # ...
    
switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    balancer:
      name: "${bms0} balancer"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    balancer:
      name: "${bms1} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"
  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"

text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    total_runtime_formatted:
      name: "${bms0} total runtime formatted"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    errors:
      name: "${bms1} errors"
    total_runtime_formatted:
      name: "${bms1} total runtime formatted"
```

```
INFO Reading configuration /config/esphome/jk_bms.yaml...
INFO Updating https://github.com/syssi/esphome-jk-bms.git@main
INFO Generating C++ source...
INFO Compiling app...
Processing jk-bms (board: wemos_d1_mini32; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
No dependencies
Compiling /data/jk-bms/.pioenvs/jk-bms/src/main.o
Linking /data/jk-bms/.pioenvs/jk-bms/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.literal._ZN7esphome10ble_client9BLEClient11dump_configEv+0xc): undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.literal._ZN7esphome10ble_client9BLEClient5setupEv+0x0): undefined reference to `esphome::esp32_ble_client::BLEClientBase::setup()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.literal._ZN7esphome10ble_client9BLEClient4loopEv+0x0): undefined reference to `esphome::esp32_ble_client::BLEClientBase::loop()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.literal._ZN7esphome10ble_client9BLEClient12parse_deviceERKNS_17esp32_ble_tracker11ESPBTDeviceE+0x0): undefined reference to `esphome::esp32_ble_client::BLEClientBase::parse_device(esphome::esp32_ble_tracker::ESPBTDevice const&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.literal._ZN7esphome10ble_client9BLEClient19gattc_event_handlerE20esp_gattc_cb_event_thP24esp_ble_gattc_cb_param_t+0x4): undefined reference to `esphome::esp32_ble_client::BLEClientBase::gattc_event_handler(esp_gattc_cb_event_t, unsigned char, esp_ble_gattc_cb_param_t*)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.literal._ZN7esphome10ble_client9BLEClient19gattc_event_handlerE20esp_gattc_cb_event_thP24esp_ble_gattc_cb_param_t+0x8): undefined reference to `esphome::esp32_ble_client::BLEService::~BLEService()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o: in function `esphome::ble_client::BLEClient::dump_config()':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:28: undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o: in function `esphome::ble_client::BLEClient::set_enabled(bool)':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:41: undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:43: undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o: in function `esphome::ble_client::BLEClient::setup()':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:16: undefined reference to `esphome::esp32_ble_client::BLEClientBase::setup()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o: in function `esphome::ble_client::BLEClient::loop()':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:21: undefined reference to `esphome::esp32_ble_client::BLEClientBase::loop()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o: in function `esphome::ble_client::BLEClient::parse_device(esphome::esp32_ble_tracker::ESPBTDevice const&)':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:34: undefined reference to `esphome::esp32_ble_client::BLEClientBase::parse_device(esphome::esp32_ble_tracker::ESPBTDevice const&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o: in function `esphome::ble_client::BLEClient::gattc_event_handler(esp_gattc_cb_event_t, unsigned char, esp_ble_gattc_cb_param_t*)':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:54: undefined reference to `esphome::esp32_ble_client::BLEClientBase::gattc_event_handler(esp_gattc_cb_event_t, unsigned char, esp_ble_gattc_cb_param_t*)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/jk-bms/src/esphome/components/ble_client/ble_client.cpp:62: undefined reference to `esphome::esp32_ble_client::BLEService::~BLEService()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.rodata._ZTVN7esphome10ble_client9BLEClientE[vtable for esphome::ble_client::BLEClient]+0x14): undefined reference to `esphome::esp32_ble_client::BLEClientBase::gap_event_handler(esp_gap_ble_cb_event_t, esp_ble_gap_cb_param_t*)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.rodata._ZTVN7esphome10ble_client9BLEClientE[vtable for esphome::ble_client::BLEClient]+0x18): undefined reference to `esphome::esp32_ble_client::BLEClientBase::connect()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.rodata._ZTVN7esphome10ble_client9BLEClientE[vtable for esphome::ble_client::BLEClient]+0x28): undefined reference to `esphome::esp32_ble_client::BLEClientBase::get_setup_priority() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/ble_client/ble_client.o:(.rodata._ZTVN7esphome10ble_client9BLEClientE[vtable for esphome::ble_client::BLEClient]+0x44): undefined reference to `non-virtual thunk to esphome::esp32_ble_client::BLEClientBase::get_setup_priority() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.o:(.literal._ZN7esphome10jk_bms_ble8JkBmsBle19gattc_event_handlerE20esp_gattc_cb_event_thP24esp_ble_gattc_cb_param_t+0x18): undefined reference to `esphome::esp32_ble_client::BLEClientBase::get_characteristic(unsigned short, unsigned short)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.o: in function `esphome::jk_bms_ble::JkBmsBle::write_register(unsigned char, unsigned int, unsigned char)':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.cpp:118: undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.o: in function `esphome::jk_bms_ble::JkBmsBle::gattc_event_handler(esp_gattc_cb_event_t, unsigned char, esp_ble_gattc_cb_param_t*)':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.cpp:144: undefined reference to `esphome::esp32_ble_client::BLEClientBase::get_characteristic(unsigned short, unsigned short)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /config/esphome/.esphome/build/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.cpp:146: undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/jk-bms/.pioenvs/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.o: in function `esphome::jk_bms_ble::JkBmsBle::update()':
/config/esphome/.esphome/build/jk-bms/src/esphome/components/jk_bms_ble/jk_bms_ble.cpp:342: undefined reference to `esphome::esp32_ble_client::BLEClientBase::address_str[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
*** [/data/jk-bms/.pioenvs/jk-bms/firmware.elf] Error 1
========================= [FAILED] Took 136.28 seconds =========================
```
