### ISSUE TITLE
Add delta cell voltage sensor

### ISSUE THREAD

**Issue by jouking** [syssi/esphome-jk-bms#21]
I don't see the delta cell vol data in the commands for esphome, doesn't that value exist?

![4831990F-E4B5-43F0-86F1-C3E1BF4BBA4A](https://user-images.githubusercontent.com/61602218/142775141-e19e973e-5687-4db7-a1bc-3dbc0de308b8.jpeg)

**Comment by syssi** [comment]
The value isn't part of the BMS response. The resistance and balancing current is missing too (and only available via Bluetooth). It would be possible to calculate min/max and the delta voltage on component level and expose it as sensor measurement.

**Comment by jouking** [comment]
and what would the sensor be like?  a template in Home Assistant?

**Comment by syssi** [comment]
My idea is to extend this component by the computed sensor.

**Comment by jouking** [comment]
ok it would be great if you could have that sensor

**Comment by syssi** [comment]
Could you try the feature branch by changing your configuration slightly:

```
external_components:
  - source: github://syssi/esphome-jk-bms@add-min-max-delta-sensors
    refresh: 0s

# [...]

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
```
