### ISSUE TITLE
E (66371) BT_BTC: btc_gattc_cback transfer failed

### ISSUE THREAD

**Issue by austin202220** [syssi/esphome-jk-bms#240]
**Issues:**

I am getting some errors in my logs and I suspect my esp32 keeps rebooting all the time. 

I have also noticed that my bms's report back as 'unavailable' status quite often, 3-4 times per hour or more. My bms, router, and esp32 are all within close proximity of less than 10 feet apart. I have tried several different esp32 chips and all are behaving the same way. I get same behavior when I run one single bms on one single esp32, and same behavior trying to run two bms's through one esp32. I believe each time they go to unavailable status the esp32 is rebooting. Also I notice by BMS's beep quite often on their own, but again, I think this is happening because the esp32 chip keeps rebooting.

**My Setup:**

I am monitoring 2 BMS's for this error report, both are connected to one ESP32-WROOM-32U
Inside esphome my esp32 chip/node is named 'jk-bms-esp32-01'
BMS #1: JK-B2A20S20P (in 16s config, device is named jk-bms-01 in home assistant and in the logs)
BMS #2: JK-BD6A20S10P (in 16s config, device is named jk-bms-02 in home assistant and in the logs)

Here are a few highlights, full logs posted seperately below: 

[13:35:34][D][esp-idf:000]: E (66371) BT_BTC: btc_gattc_cback transfer failed

[13:35:53][D][jk_bms_ble:630]: Unknown158: 64 00 (always 0x64 0x00?)
[13:35:53][D][jk_bms_ble:633]: Unknown160: 5E 06 (always 0xC5 0x09?)
[13:35:56][D][jk_bms_ble:899]:   Unknown6: 0.600000

[13:37:43][D][jk_bms_ble:630]: Unknown158: 64 00 (always 0x64 0x00?)
[13:37:43][D][jk_bms_ble:633]: Unknown160: E5 04 (always 0xC5 0x09?)
[13:37:43][D][sensor:127]: 'jk-bms-02 total runtime': Sending state 318313.00000 s with 0 decimals of accuracy
[13:37:43][D][text_sensor:067]: 'jk-bms-02 total runtime formatted': Sending state '3d 16h'
[13:37:43][D][jk_bms_ble:646]: Unknown168: 61.06.00.00.00.00.00.00.00.00.00.00.00.00.07.00.01.00.00.00.C3.03.34.00.00.00.A7.C9.3F.40.00.00.00.00.E2.04.00.00.00.00.00.01.00.05.00.00 (46)
[13:37:43][D][jk_bms_ble:660]: Unknown189: 03 34
[13:37:43][D][jk_bms_ble:664]: Unknown192: 00
[13:37:43][D][jk_bms_ble:666]: Unknown193: 00 A7 (0x00 0x8D)
[13:37:43][D][jk_bms_ble:668]: Unknown195: C9 3F (0x21 0x40)

I have these running separately, can be used for testing too if needed:
JK-B1A20S15P (pending install, will be 16s config)
JK-BD4A8S4P (two of these in 4s config, running on two different esp32's
[logs_jk-bms-esp32-01_logs (7).txt](https://github.com/syssi/esphome-jk-bms/files/10503227/logs_jk-bms-esp32-01_logs.7.txt)
)

[jk-bms-esp32-01 (2).yaml.txt](https://github.com/syssi/esphome-jk-bms/files/10503257/jk-bms-esp32-01.2.yaml.txt)

**Comment by syssi** [comment]
Please try the following experiment:

1. Talk to a single BMS
2. Reduce the number of entities to f.e. 3 sensors
3. Decrease the log level from `DEBUG` to `INFO`
4. Use the native `api` instead of `mqtt` if possible

This will free a lot of resources / reduce the load. Every beep of the BMS indicates a "reconnect" it doesn't need to be a reboot of the ESP. In best case you can consume the log of ESPHome using the serial interface instead of using WiFi. In this case you should see every crash or BLE connection retry. Does this experiment stabilize the BLE connection / reduce the number of BMS beeps per hour?

**Comment by austin202220** [comment]
> 4\. Use the native `api` instead of `mqtt` if possible

How do I make the change to use native apt instead of mqtt? From reading my yaml code I dont see any references to mqtt?

**Comment by syssi** [comment]
If you use the native `api` already there should be a `api:` section at your yaml. If you are using MQTT there should be an `mqtt:` section plus some parameters.

**Comment by austin202220** [comment]
I posted my full yaml config as an attachment in the original post, I am already using the native api and not mqtt

```
substitutions:
  name: jk-bms
  bms0: "${name}-01"
  bms1: "${name}-02"
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  bms0_mac_address: C8:47:8C:xx:xx:xx
  bms1_mac_address: C8:47:8C:xx:xx:xx
  # Defaults to "JK02". Please use "JK04" if you have some old JK-BMS version (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  bms0_protocol_version: JK02
  bms1_protocol_version: JK02


esphome:
  name: ${name}-esp32-01
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.3.0


esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s


# Enable logging
logger:
    level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${bms0_protocol_version}
    throttle: 5s
    id: bms0
  - ble_client_id: client1
    protocol_version: ${bms1_protocol_version}
    throttle: 5s
    id: bms1

binary_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"

button:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    retrieve_settings:
      name: "${bms0} retrieve settings"
    retrieve_device_info:
      name: "${bms0} retrieve device info"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    retrieve_settings:
      name: "${bms1} retrieve settings"
    retrieve_device_info:
      name: "${bms1} retrieve device info"

number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${bms0} balance trigger voltage"
    cell_count:
      name: "${bms0} cell count"
    total_battery_capacity:
      name: "${bms0} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${bms0} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${bms0} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${bms0} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${bms0} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${bms0} balance starting voltage"
    voltage_calibration:
      name: "${bms0} voltage calibration"
    current_calibration:
      name: "${bms0} current calibration"
    power_off_voltage:
      name: "${bms0} power off voltage"
    max_balance_current:
      name: "${bms0} max balance current"
    max_charge_current:
      name: "${bms0} max charge current"
    max_discharge_current:
      name: "${bms0} max discharge current"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    balance_trigger_voltage:
      name: "${bms1} balance trigger voltage"
    cell_count:
      name: "${bms1} cell count"
    total_battery_capacity:
      name: "${bms1} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${bms1} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${bms1} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${bms1} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${bms1} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${bms1} balance starting voltage"
    voltage_calibration:
      name: "${bms1} voltage calibration"
    current_calibration:
      name: "${bms1} current calibration"
    power_off_voltage:
      name: "${bms1} power off voltage"
    max_balance_current:
      name: "${bms1} max balance current"
    max_charge_current:
      name: "${bms1} max charge current"
    max_discharge_current:
      name: "${bms1} max discharge current"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${bms0} min cell voltage"
    max_cell_voltage:
      name: "${bms0} max cell voltage"
    min_voltage_cell:
      name: "${bms0} min voltage cell"
    max_voltage_cell:
      name: "${bms0} max voltage cell"
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    average_cell_voltage:
      name: "${bms0} average cell voltage"
    cell_voltage_1:
      name: "${bms0} cell voltage 1"
    cell_voltage_2:
      name: "${bms0} cell voltage 2"
    cell_voltage_3:
      name: "${bms0} cell voltage 3"
    cell_voltage_4:
      name: "${bms0} cell voltage 4"
    cell_voltage_5:
      name: "${bms0} cell voltage 5"
    cell_voltage_6:
      name: "${bms0} cell voltage 6"
    cell_voltage_7:
      name: "${bms0} cell voltage 7"
    cell_voltage_8:
      name: "${bms0} cell voltage 8"
    cell_voltage_9:
      name: "${bms0} cell voltage 9"
    cell_voltage_10:
      name: "${bms0} cell voltage 10"
    cell_voltage_11:
      name: "${bms0} cell voltage 11"
    cell_voltage_12:
      name: "${bms0} cell voltage 12"
    cell_voltage_13:
      name: "${bms0} cell voltage 13"
    cell_voltage_14:
      name: "${bms0} cell voltage 14"
    cell_voltage_15:
      name: "${bms0} cell voltage 15"
    cell_voltage_16:
      name: "${bms0} cell voltage 16"
    cell_resistance_1:
      name: "${bms0} cell resistance 1"
    cell_resistance_2:
      name: "${bms0} cell resistance 2"
    cell_resistance_3:
      name: "${bms0} cell resistance 3"
    cell_resistance_4:
      name: "${bms0} cell resistance 4"
    cell_resistance_5:
      name: "${bms0} cell resistance 5"
    cell_resistance_6:
      name: "${bms0} cell resistance 6"
    cell_resistance_7:
      name: "${bms0} cell resistance 7"
    cell_resistance_8:
      name: "${bms0} cell resistance 8"
    cell_resistance_9:
      name: "${bms0} cell resistance 9"
    cell_resistance_10:
      name: "${bms0} cell resistance 10"
    cell_resistance_11:
      name: "${bms0} cell resistance 11"
    cell_resistance_12:
      name: "${bms0} cell resistance 12"
    cell_resistance_13:
      name: "${bms0} cell resistance 13"
    cell_resistance_14:
      name: "${bms0} cell resistance 14"
    cell_resistance_15:
      name: "${bms0} cell resistance 15"
    cell_resistance_16:
      name: "${bms0} cell resistance 16"
    total_voltage:
      name: "${bms0} total voltage"
    current:
      name: "${bms0} current"
    power:
      name: "${bms0} power"
    charging_power:
      name: "${bms0} charging power"
    discharging_power:
      name: "${bms0} discharging power"
    temperature_sensor_1:
      name: "${bms0} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0} temperature sensor 2"
    power_tube_temperature:
      name: "${bms0} power tube temperature"
    state_of_charge:
      name: "${bms0} state of charge"
    capacity_remaining:
      name: "${bms0} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms0} total battery capacity setting"
    charging_cycles:
      name: "${bms0} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms0} total charging cycle capacity"
    total_runtime:
      name: "${bms0} total runtime"
    balancing_current:
      name: "${bms0} balancing current"
    errors_bitmask:
      name: "${bms0} errors bitmask"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    min_cell_voltage:
      name: "${bms1} min cell voltage"
    max_cell_voltage:
      name: "${bms1} max cell voltage"
    min_voltage_cell:
      name: "${bms1} min voltage cell"
    max_voltage_cell:
      name: "${bms1} max voltage cell"
    delta_cell_voltage:
      name: "${bms1} delta cell voltage"
    average_cell_voltage:
      name: "${bms1} average cell voltage"
    cell_voltage_1:
      name: "${bms1} cell voltage 1"
    cell_voltage_2:
      name: "${bms1} cell voltage 2"
    cell_voltage_3:
      name: "${bms1} cell voltage 3"
    cell_voltage_4:
      name: "${bms1} cell voltage 4"
    cell_voltage_5:
      name: "${bms1} cell voltage 5"
    cell_voltage_6:
      name: "${bms1} cell voltage 6"
    cell_voltage_7:
      name: "${bms1} cell voltage 7"
    cell_voltage_8:
      name: "${bms1} cell voltage 8"
    cell_voltage_9:
      name: "${bms1} cell voltage 9"
    cell_voltage_10:
      name: "${bms1} cell voltage 10"
    cell_voltage_11:
      name: "${bms1} cell voltage 11"
    cell_voltage_12:
      name: "${bms1} cell voltage 12"
    cell_voltage_13:
      name: "${bms1} cell voltage 13"
    cell_voltage_14:
      name: "${bms1} cell voltage 14"
    cell_voltage_15:
      name: "${bms1} cell voltage 15"
    cell_voltage_16:
      name: "${bms1} cell voltage 16"
    cell_resistance_1:
      name: "${bms1} cell resistance 1"
    cell_resistance_2:
      name: "${bms1} cell resistance 2"
    cell_resistance_3:
      name: "${bms1} cell resistance 3"
    cell_resistance_4:
      name: "${bms1} cell resistance 4"
    cell_resistance_5:
      name: "${bms1} cell resistance 5"
    cell_resistance_6:
      name: "${bms1} cell resistance 6"
    cell_resistance_7:
      name: "${bms1} cell resistance 7"
    cell_resistance_8:
      name: "${bms1} cell resistance 8"
    cell_resistance_9:
      name: "${bms1} cell resistance 9"
    cell_resistance_10:
      name: "${bms1} cell resistance 10"
    cell_resistance_11:
      name: "${bms1} cell resistance 11"
    cell_resistance_12:
      name: "${bms1} cell resistance 12"
    cell_resistance_13:
      name: "${bms1} cell resistance 13"
    cell_resistance_14:
      name: "${bms1} cell resistance 14"
    cell_resistance_15:
      name: "${bms1} cell resistance 15"
    cell_resistance_16:
      name: "${bms1} cell resistance 16"
    total_voltage:
      name: "${bms1} total voltage"
    current:
      name: "${bms1} current"
    power:
      name: "${bms1} power"
    charging_power:
      name: "${bms1} charging power"
    discharging_power:
      name: "${bms1} discharging power"
    temperature_sensor_1:
      name: "${bms1} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms1} temperature sensor 2"
    power_tube_temperature:
      name: "${bms1} power tube temperature"
    state_of_charge:
      name: "${bms1} state of charge"
    capacity_remaining:
      name: "${bms1} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms1} total battery capacity setting"
    charging_cycles:
      name: "${bms1} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms1} total charging cycle capacity"
    total_runtime:
      name: "${bms1} total runtime"
    balancing_current:
      name: "${bms1} balancing current"
    errors_bitmask:
      name: "${bms1} errors bitmask"      

switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"
    balancer:
      name: "${bms0} balancer"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"
    balancer:
      name: "${bms1} balancer"

  - platform: ble_client
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"
  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"

text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    total_runtime_formatted:
      name: "${bms0} total runtime formatted"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms1
    errors:
      name: "${bms1} errors"
    total_runtime_formatted:
      name: "${bms1} total runtime formatted"
```
