### ISSUE TITLE
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program as compilation terminated.

### ISSUE THREAD

**Issue by JohnGalt1717** [syssi/esphome-jk-bms#256]
Compiling .pioenvs/bmses/driver/periph_ctrl.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program as
compilation terminated.
*** [.pioenvs/bmses/src/main.o] Error 1

I get this as soon as I add any of the - number: components. Doesn't matter which.

I've done a clean.

Everything else works perfectly.

**Comment by syssi** [comment]
Interesting. Which ESPHome version do you use and what's the CPU architecture of the build host?

**Comment by JohnGalt1717** [comment]
Here's the board/cpu:

```
esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: latest

```

And it's using the latest esphome in docker.
