### ISSUE TITLE
Bricked BMS after OTA using ESP32

### ISSUE THREAD

**Issue by tmarkson** [syssi/esphome-jk-bms#28]
Whatsup @syssi I was trying your code via ESPhome and managed to brick my JKBMS 8s20p model.  Now the buzzer beeps repeatedly and connecting to bluetooth doesn't show any battery info. 

I have another one in hand as of Jan 16 so I'm sticking to software UART, still trying your code. 

I used an ESP32 on the hardware UART.  The first time with that connected, I used OTA to send the changed firmware.  After the short waiting period for the OTA firmware to move from flash to program memory, it bricked.  The fast beeping started and I was unable to revive the BMS.  
 
That was after a soft reset by the ESP to initialize the new firmware.  My guess is there is some UART data sent during boot that caused a bad state to the BMS. 

Here is my config that did the deed. ...

```
### esp32-jkbms-bridge.yaml
# ESP32 dev board connected to JK-BMS via hardware UART, pins IO1 and IO3.
#
# Included project: https://github.com/syssi/esphome-jk-bms
# Target hardware is JK-B2A8S20P

substitutions:
  devicename: "esp32-jkbms-bridge"
  deviceid: "esp32_jkbms_bridge"

esphome:
  name: "${devicename}"
  platform: ESP32
  board: nodemcu-32s

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

wifi:
  ssid: !secret ssid_home
  password: !secret pass_home
  fast_connect: true

ota:
logger:
  baud_rate: 0
  level: DEBUG

api:

uart:
  id: uart0
  baud_rate: 115200
  rx_buffer_size: 384
  tx_pin: TX
  rx_pin: RX

jk_modbus:
  id: modbus0
  uart_id: uart0

jk_bms:
  id: bms0
  jk_modbus_id: modbus0

sensor:
  - platform: jk_bms
    min_cell_voltage:
      name: "${devicename} min cell voltage"
```
