### ISSUE TITLE
Change mqtt-port possible?

### ISSUE THREAD

**Issue by cyrano330** [syssi/esphome-jk-bms#294]
Hi guys,

is there a possibility to make the mqtt port configurable? Also the Topics etc.?

I've the problem, that I can not receive data via mqtt - but can't configure anything...

Best Henry

**Comment by syssi** [comment]
This is the documentation of the `mqtt` component of ESPHome:

https://esphome.io/components/mqtt.html

```
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  id: mqtt_client
```
