### ISSUE TITLE
How to increase the stack size?

### ISSUE THREAD

**Issue by rfenouil** [syssi/esphome-jk-bms#303]
Thank you for this work, this library is awesome !

I am using the 'esp32-ble-multiple' template to connect to 2 BMS (ebike batteries), and when I add too many sensors I get into the boot loop problem.

I tried increasing the stack size as you suggested [here](https://github.com/syssi/esphome-jk-bms/issues/63#issuecomment-1093130049), but it did not help:

```
esphome:
  name: ${name}
  platformio_options:
    build_flags:
       - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=65535
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 1.4.0
```

I also tried to set `DARDUINO_LOOP_STACK_SIZE` as I found a reference to this name during my search but it did not help either.

Can you spot something wrong with my declaration above ?

Thank you for your help !

My esphome version (docker): 2023.3.2
