### ISSUE TITLE
Change current sign

### ISSUE THREAD

**Issue by SeByDocKy** [syssi/esphome-jk-bms#40]
Hi,

I noticed that current is actually signed negatively while charging while in the Appz it's positive. Is-it possible to integrate this very tiny minor change ?

**Comment by syssi** [comment]
Please take a look at https://github.com/syssi/esphome-jk-bms/issues/36 and https://github.com/syssi/esphome-jk-bms/issues/23. I assume the sign is correct for some firmware versions. Flipping the sign now is a breaking change I would like to avoid as long as we aren't 100% sure. Please fix the issue by applying a filter

```
     current:
      name: "${name} current"
      filters:
        - multiply: -1
```
