### ISSUE TITLE
Unstable connecting to more than one BMS over BLE

### ISSUE THREAD

**Issue by octane321** [syssi/esphome-jk-bms#437]
Hi there,
i tried to get multiple BMSs connecting over BLE - but if a activate all (for me) relevant sensors with two JKs, the esp is getting very instable and crashes every 5-20 minutes. Goal would be to connect to 3 JKs

i tried to debug the situation and think the heap is the problem.
Could it be a possible solution using an ESP-CAM or WROVER with 4/8MB PSRAM to increase the available heap?

**Comment by octane321** [comment]
I also added delta Filter on all sensors to reduce publishing to mqtt broker wich helps a bit

`    - platform: jk_bms_ble
      jk_bms_ble_id: jk_bms_ble_JK_BMS2
    # voltages
      total_voltage:
        id: total_voltage_bms2
        name: "BMS2 Voltage"
        filters:
          - delta: 0.01
        state_topic: ${prefix}/${subtopic}/JK_BMS2/01_Battery/01_Voltage`

**Comment by syssi** [comment]
Decreasing the log level to `INFO` or `WARN` should free some resources too. I don't if there are ESP32 flavors which will improve the situation. If you have the chance you could try to avoid WiFi and use a ethernet connection instead. IMO concurrency (WiFi vs. BLE) is also responsible for stability issues.

Are you aware of the `throttle` parameter to drop readings? The JK-BMS publishes frames/notifications in a fixed interval (0.5s) which cannot be controlled. Throwing frames away is the only option to reduce the update interval.

**Comment by syssi** [comment]
Some more options you could play around with:

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
```

```
esp32_ble_tracker:
  scan_parameters:
    interval: 500ms
```
