### ISSUE TITLE
Disconnecting from bluetooth

### ISSUE THREAD

**Issue by sarzyk** [syssi/esphome-jk-bms#512]
![Uploading Screenshot_20240624_133918_Allegro.jpg…]()
Hi. I bought this esp32 device:

I make everything like in tutorial but I have a problem.
The device randomly disconnected all the time.
What could be a reason this situation?

**Comment by rt1970** [comment]
On my ESP32 via BLE too. BMS make frequently a beep...
How can i set MQTT Update-Interval?

**Comment by syssi** [comment]
The BMS pushes data every 0.5s. You can use the `throttle` parameter to skip most of the data:

```
jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 60s
```

This setting publishes a set of measurements once per minute.

IMO this setting is useless:

```
    on_passkey_request:
      then:
        - ble_client.passkey_reply:
            id: client0
            passkey: 1234
```

The BLE module of the BMS is unable to do authentication/encryption.
