### ISSUE TITLE
JKPB2A16SXXP: Temperature sensors 3 and 4 not reported

### ISSUE THREAD

**Issue by holle75** [syssi/esphome-jk-bms#519]
https://github.com/syssi/esphome-jk-bms/issues/517#issuecomment-2212388919

temp sensors 3 and 4 (i suppose) are not registered/communicated

**Comment by syssi** [comment]
Could you increase the log level to `VERY_VERBOSE` and provide some raw data of the `cell info frame`?

https://github.com/syssi/esphome-jk-bms/blob/main/components/jk_bms_ble/jk_bms_ble.cpp#L329-L331

```
logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble_tracker: VERY_VERBOSE
    jk_bms_ble: VERY_VERBOSE
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```
