### ISSUE TITLE
JKPBXA16SXXP: "switch" settings when restart

### ISSUE THREAD

**Issue by holle75** [syssi/esphome-jk-bms#531]
Hi, minor one.

It seems when restarting, the switch settings (charging, charging float mode, display always on, ecc) are not read/set. I have to "click" the "retrieve settings" button to get them shown in the ESP dashboard.

Funny thing is that the overhead in my MQTT server is getting higher when those settings are not defined in the ESP.

question is: any way to read those settings during startup?

**Comment by syssi** [comment]
This is a duplicate. Please subscribe this issue to track the progress here: #292

**Comment by syssi** [comment]
If you want to request the settings frame periodically, you could do something like this:

```
button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name} retrieve settings"
      id: retrieve_settings_button
    retrieve_device_info:
      name: "${name} retrieve device info"

interval:
  - interval: 30min
    then:
      - button.press: retrieve_settings_button
```

Keep in mind: The BMS will beep on every request.
