### ISSUE TITLE
Inverter BMS battery capacity not reporting correctly

### ISSUE THREAD

**Issue by iamvlanone** [syssi/esphome-jk-bms#535]
I connected a 250Ah battery and all data seemed correct between JK BMS App and ESP. Somehow this changed and the ESP sensor is now reporting 161Ah while the BMS still reports 250Ah in the JK BMS App. 

23:05:22][D][sensor:094]: 'inv-batt-1 capacity remaining': Sending state 161.24701 Ah with 3 decimals of accuracy
[23:05:22][D][sensor:094]: 'inv-batt-1 total battery capacity setting': Sending state 161.24701 Ah with 0 decimals of accuracy

Any ideas or guidance on where to look?

**Comment by syssi** [comment]
If you increase the log level the raw data of the BMS is printed to the log. This raw data would be helpful to get an idea what's going on here. Do use use a BLE or UART connection? Do you know how to increase the log level?

**Comment by iamvlanone** [comment]
Sorry, I am using BLE. I saw the section on increasing the log level. Should I increase all the levels or is there a specific one in order to minimize the amount of output?

**Comment by syssi** [comment]
This is the required logger configuration for a BLE setup:

```
logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble_tracker: VERY_VERBOSE
    jk_bms_ble: VERY_VERBOSE
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```

I'm interested in all `jk_bms_ble` and `sensor` log messages.
