### ISSUE TITLE
Make "RCV Time" and "RFV Time" controllable

### ISSUE THREAD

**Issue by dmode9000** [syssi/esphome-jk-bms#548]
Could you please let me know if the "RCV Time" and "RFV Time" parameters are available? I haven't found them in the HA interface yet and haven't found any information on how to add them to the interface.

**Comment by syssi** [comment]
How do you talk to your BMS? If you are using BLE the feature was added here: https://github.com/syssi/esphome-jk-bms/issues/422

You can just add these additional `number` entities to your configuration YAML: https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-v14-example.yaml#L132-L135

**Comment by syssi** [comment]
Oh. We are talking about the runtimes. This setting isn't implemented yet.

```
# RCV time
aa:55:90:eb: b3 :01: 14 :71:55:0b:ba:97:e6:68:67:fe:71:5b:50:33 # 20 * 0.1f = 2.0h
aa:55:90:eb: b3 :01: 0a :76:55:c2:22:63:4f:02:ce:a8:d8:a7:0a:9a # 10 * 0.1f = 1.0h

# RFV time
aa:55:90:eb: b4 :01: 5a :45:6a:43:1a:4d:85:5f:3e:db:6a:f8:73:b4 # 90 * 0.1f = 9.0h
aa:55:90:eb: b4 :01: 50 :d1:61:5a:d0:53:35:21:c9:8a:63:ec:6d:93 # 80 * 0.1f = 8.0h
```

This issue is the follow up of #422 because two feature was missing.

**Comment by syssi** [comment]
I've started to implement the feature but some testing is required to complete the feature. Are you able to talk to your BMS already? Could you offer some testing?

**Comment by dmode9000** [comment]
Yes, I can test it. Do I understand correctly that after recompiling and flashing in Homeassisant, these parameters should appear as available?

**Comment by syssi** [comment]
You have to extend your YAML configuration be these 4 lines at the `number` section:

https://github.com/syssi/esphome-jk-bms/blob/main/esp32-ble-v14-example.yaml#L136-L139

```
number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    # ...
    cell_request_charge_voltage_time:
      name: "${name} cell request charge voltage time"
    cell_request_float_voltage_time:
      name: "${name} cell request float voltage time"
``` 

And recompile + flash your ESP. The two number entities are populated as soon a `device info`  frame gets received. This frame is retrieved once on an established BLE connection and can be trieved manually using the `retrieve device info` button.
