### ISSUE TITLE
UART Discharging switch not working ( B2A20S20P HW: V11.XW - SW: V11.285H )

### ISSUE THREAD

**Issue by Sleeper85** [syssi/esphome-jk-bms#559]
Hi @syssi 

First of all, thank you very much for all the development you have done to integrate the different brands of BMS into HA.

I'm testing the UART switches and I realize that the `discharging` switch does not work from HA.
I can modify it in the JK application and its status will be updated in HA but I cannot modify it from HA.

The `charging` switch works fine.

Is this a known issue with the `V11.285H` version?

```YAML
switch:
  - platform: jk_bms
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
```

Many thanks
