### ISSUE TITLE
 2 BMS CONNECTION PROBLEM

### ISSUE THREAD

**Issue by jouking** [syssi/esphome-jk-bms#560]
I have been trying for three days to get an esp32 and a wemo d1 connected via UART-TTL to the bms of my second power bank to work but I am not able to, let's see if someone can help me because I am desperate. 

**I have 2 black jkbms in 2 power banks.** 

### The first one is connected through the rs485 port via UART-TTL to an ESP WT32-ETH01 with the configuration that I indicate below and it works perfectly. 

Now in my second power bank I bought another identical WT32-ETH01 and I have connected it the same as the first and I get this error:

```
[17:29:37][D][text_sensor:064]: 'w32-banco2 Errors': Sending state 'Offline'
[17:29:37][D][sensor:094]: 'w32-banco2 min cell voltage': Sending state nan V with 3 decimals of accuracy
[17:29:37][D][sensor:094]: 'w32-banco2 max cell voltage': Sending state nan V with 3 decimals of accuracy
[17:29:37][D][sensor:094]: 'w32-banco2 min voltage cell': Sending state nan  with 0 decimals of accuracy
[17:29:37][D][sensor:094]: 'w32-banco2 max voltage cell': Sending state nan  with 0 decimals of accuracy 
```

When I put the WT32-ETH01 from bank 1 in bank 2 it works correctly, but I cannot get the new ESP WT32-ETH01 to work. 

I have tried connecting bank 2 with a Wemo D1 in case the new WT32-ETH01 did not work, but it does the same. 

What am I doing wrong?

CODE:

```
substitutions:
  name: w32-banco2

esphome:
  name: ${name}
  friendly_name: w32_banco2
  platform: ESP32
  board: esp-wrover-kit

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1u757XEy/uOj/WcvTB7RpaSjGJx+PfiE7Mqspw="

ota:
  - platform: esphome
    password: "6299d3d3d0ec7414ff477302d"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

# Optional manual IP
  manual_ip:
    static_ip: 192.168.1.196
    gateway: 192.168.1.254
    subnet: 255.255.255.0

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: GPIO3
    rx_pin: GPIO1


jk_modbus:
  - id: modbus0
    uart_id: uart_0
#  rx_timeout: 50ms

jk_bms:
  - id: bms0
    jk_modbus_id: modbus0
#  update_interval: 5s

sensor:
  - platform: jk_bms
    jk_bms_id: bms0
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
    cell_voltage_17:
      name: "${name} cell voltage 17"
    cell_voltage_18:
      name: "${name} cell voltage 18"
    power_tube_temperature:
      name: "${name} Power tube temperature"
    temperature_sensor_1:
      name: "${name} Temperature sensor 1"
    temperature_sensor_2:
      name: "${name} Temperature sensor 2"
    total_voltage:
      name: "${name} Total voltage"
    current:
      name: "${name} Current"
    capacity_remaining:
      name: "${name} Capacity remaining"
    capacity_remaining_derived:
      name: "${name} capacity remaining derived"
    temperature_sensors:
      name: "${name} Temperature sensors"
    charging_cycles:
      name: "${name} Charging cycles"
    total_charging_cycle_capacity:
      name: "${name} Total charging cycle capacity"
    battery_strings:
      name: "${name} Battery strings"
    errors_bitmask:
      name: "${name} Errors bitmask"
    operation_mode_bitmask:
      name: "${name} Operation mode bitmask"
    total_voltage_overvoltage_protection:
      name: "${name} Total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      name: "${name} Total voltage undervoltage protection"
    cell_voltage_overvoltage_protection:
      name: "${name} Cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} Cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} Cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      name: "${name} Cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} Cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} Cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      name: "${name} Cell pressure difference protection"
    discharging_overcurrent_protection:
      name: "${name} Discharging overcurrent protection"
    discharging_overcurrent_delay:
      name: "${name} Discharging overcurrent delay"
    charging_overcurrent_protection:
      name: "${name} Charging overcurrent protection"
    charging_overcurrent_delay:
      name: "${name} Charging overcurrent delay"
    balance_starting_voltage:
      name: "${name} Balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} Balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} Power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} Power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} Temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} Temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} Temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      name: "${name} Charging high temperature protection"
    discharging_high_temperature_protection:
      name: "${name} Discharging high temperature protection"
    charging_low_temperature_protection:
      name: "${name} Charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} Charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} Discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} Discharging low temperature recovery"
    current_calibration:
      name: "${name} Current calibration"
    device_address:
      name: "${name} Device address"
    sleep_wait_time:
      name: "${name} Sleep wait time"
    alarm_low_volume:
      name: "${name} Alarm low volume"
    manufacturing_date:
      name: "${name} Manufacturing date"
    total_runtime:
      name: "${name} Total runtime"
    start_current_calibration:
      name: "${name} start current calibration"
    actual_battery_capacity:
      name: "${name} Actual battery capacity"
    protocol_version:
      name: "${name} Protocol version"
      
text_sensor:
  - platform: jk_bms
    errors:
      name: "${name} Errors"
    operation_mode:
      name: "${name} Operation mode"
    battery_type:
      name: "${name} Battery type"
    password:
      name: "${name} Password"
    device_type:
      name: "${name} Device type"
    software_version:
      name: "${name} Software version"
    manufacturer:
      name: "${name} Manufacturer"

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"
```

![5872785689408553752](https://github.com/user-attachments/assets/82fa8345-05f4-4fff-9a44-c15ed37e2911)
![5872785689408553753](https://github.com/user-attachments/assets/cfed1d4f-0289-4346-a7f5-d82b54f27ee9)

**Comment by syssi** [comment]
Please don't use the TXD and RXD pin. The USB-to-TTL chip is attached here and the BMS doesn't like this. Please use any other GPIO instead.

**Comment by syssi** [comment]
Oh. Is there a USB-to-TTL chip on the WT32-ETH01? Nevertheless. Please try other GPIOs. :-)

**Comment by jouking** [comment]
> Please don't use the TXD and RXD pin. The USB-to-TTL chip is attached here and the BMS doesn't like this. Please use any other GPIO instead.

I tried with GPIO14 and GPIO4 and the problem continues.

**Comment by jouking** [comment]
Anyway the wt32 of bank 1 works perfectly on the GPIO3 and GPIO1

**Comment by syssi** [comment]
Are you sure you haven't swapped the RX/TX lines accidentally?

Another idea is to use the ESP-IDF framework just for testing:

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
```
