### ISSUE TITLE
Help with MQTT publishing from node-red via Mosquito

### ISSUE THREAD

**Issue by Phil-b-l** [syssi/esphome-jk-bms#619]

**Comment by Phil-b-l** [comment]
Oops tried to delete query as solved it but couldn't so appear to have closed a blank. Sorry

**Comment by syssi** [comment]
Did find all topics and required payloads + did you disable the auto-discovery topics?

**Comment by Phil-b-l** [comment]
Hi
I installed MQTT Explorer and that showed me what was expected and I also realised that I had built a version where the yml didn't include those options and, while I had edited it to inlude some stuff that wasn't in the original, that was a switch I hadn't added. I have now rebuilt with the full selection and just deleted what I don't need in an attempt to be kind to my poor little pi and its mosquito which is working rather hard. I might try and turn off the debug as that seems to rather flood it.

Thanks very much for creating this and for taking the time to respond. It is much appreciated

Kind Regards

Phil

**Comment by syssi** [comment]
If you don't use Home Assistant you could disable the discovery topic to get rid of some more traffic:

```
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
  discovery: false
```
