### ISSUE TITLE
Settings are changing by itself 

### ISSUE THREAD

**Issue by informatuss** [syssi/esphome-jk-bms#636]
Few settings are changing by itself after few hours. In log there is no indication why.

![Screenshot_20241209-065157 (1)](https://github.com/user-attachments/assets/43c7c2bb-7cc9-43c8-8a87-1db2959ad11b)
![Screenshot_20241209-065205 (1)](https://github.com/user-attachments/assets/0f476679-220d-4d60-a553-e430d4bd8dcf)
![Screenshot_20241209-065239 (1)](https://github.com/user-attachments/assets/5af6994b-1b6b-485f-a850-7be7dd8b0d33)

**Comment by syssi** [comment]
Could you describe your setup in a few words? Which YAML configuration do you use?

**Comment by janas-karol** [comment]
> Could you describe your setup in a few words? Which YAML configuration do you use?

I'm using ESP32 via bluetooth. Used esp32-ble-example.yaml. 
Everything is working great (thx for you work btw ;)) but these setting keep changing to default. I'm not connecting phone with app or anything, it looks random to me.

**Comment by syssi** [comment]
Could you enable the `VERY_VERBOSE` output of the component by:

```
logger:
  level: VERY_VERBOSE
  logs:
    esp32_ble_tracker: INFO
    jk_bms_ble: VERY_VERBOSE
    scheduler: INFO
    component: INFO
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```

I would like to compare the random value with the RAW payload of the BLE notification.
