### ISSUE TITLE
JK BMS beep while polling

### ISSUE THREAD

**Issue by ouinouin** [syssi/esphome-jk-bms#664]
Hi, just gone from daly (after one DOA and one not working after 2 month.) to JK bms, 

i m using the bluetooth communication, the issue is that from times to times there is a beep coming frome the MS, this is the same beep we hear while changin the settings in the officiall application, i found nowere in the application for this beep to be removed.
so i m guessing there are categories , and its while ths bluetooth is polling from the values to the settings that the beep occurs. (i couldnt find a specific time when it occurs, i was thinking it was tied to my polling time but i have difficulties to see a scheme.
i sent a message to JK in parallel to ask if they can add in their firmware a toggle for this useless beep (at least in stationnary setups)

```
substitutions:
  name: "lacoume-bt-devices"
  device_description: "full monitor of lacoume"
  mac_address: C8:47:80:26:29:62
  protocol_version: JK02_32S
esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-daly-bms"
    version: 1.0.0

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble
  - source: github://syssi/esphome-jk-bms@main
  - source: github://syssi/esphome-daly-bms@main


wifi:
  networks:
    - ssid: mifimiji
      password: paswoooooooord
      manual_ip:
        static_ip: 192.168.7.253
        gateway: 192.168.7.254
        subnet: 255.255.255.0
    - ssid: ouinouin_Nicol
      password: paswoooooooord
ota:
  platform: esphome

web_server:
  port: 80
  version: 1

logger:
#  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client
mqtt:
  broker: 192.168.7.254
api:
  #encryption:
  #  key: "ofaI6e0mYZ28/PNNKv09lBuRQmwDU1+hoy8o9ztNyWg="
  reboot_timeout: 0s
esp32_ble_tracker:
  scan_parameters:
    active: false
    interval: 2s

ble_client:
  - mac_address: ${mac_address}
    id: client0

#BMS_bms_ble:
#  - ble_client_id: client0
#    id: bms0
#    password: 12345678
#    update_interval: 30s

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0
    update_interval: 30s

victron_ble:
    #smartsolar 100|30
  - id: lacoumeSmartSolar
    mac_address: "eb:70:30:7e:67:f5"
    bindkey: "paswoooooooord"
  - id: lacoume1600VA
    mac_address: "df:aa:72:d0:60:1e"
    bindkey: "paswoooooooord"
  - id: bmv700
    mac_address: "f8:83:04:c5:33:37"
    #bindkey: "paswoooooooord"
    bindkey: "paswoooooooord"

binary_sensor:
     #daly
  - platform: jk_bms_ble
    balancing:
      id: BMS_balancing
    charging:
      id: BMS_charging
    discharging:
      id: BMS_discharging
#    heating:
#      name: "${name} heating"
#    online_status:
#      name: "${name} online status"






# values to cast ? 
  - platform: template
    name: "BMS balancing"
    id: BMS_balancing_ext

  - platform: template
    name: "BMS charging"
    id: BMS_charging_ext

  - platform: template
    name: "BMS discharging"
    id: BMS_discharging_ext

  - platform: template
    name: "inverter 1600VA fault"
    id: inverter_1600VA_fault_ext

  - platform: template
    name: "MPPT 100-30 is in Fault state"
    id : MPPT_100_30_Fault_state_ext
    #id: MPPTFaultstate_ext

  - platform: template
    name: "inverter 1600VA Alarm state"
    id: inverter_1600VA_Alarm_state_ext


  - platform: template
    name: "inverter 1600VA is on/off"
    id: inverter_1600_onoff_state_ext


  - platform: template
    name: "MPPT 100-30 has Error"
    id: MPPTerrortstate_ext
    #lambda: !lambda |-
    #  return id(MPPT_100_30_error_state).state;




#     #victron
#     # mppt 100-30
    # device fault
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar 
    id: MPPT_100_30_Fault_state
    type: DEVICE_STATE_FAULT

   #device error
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar
    id: MPPT_100_30_error_state
    type: CHARGER_ERROR

    # inverter 1600VA
    #alarm state
  - platform: victron_ble
    victron_ble_id: lacoume1600VA
    id: inverter_1600_alarm_state
    type: ALARM

    #onoff state
  - platform: victron_ble
    victron_ble_id: lacoume1600VA
    id : inverter_1600_onoff_state
    type: DEVICE_STATE_OFF

    #Faultstate
  - platform: victron_ble
    victron_ble_id: lacoume1600VA
    id: inverter_1600_fault_state
    type: DEVICE_STATE_FAULT


#republish
interval:
  - interval: 60s
    then: 
      - binary_sensor.template.publish:
          id: BMS_balancing_ext
          state: !lambda 'return id(BMS_balancing).state ;'
      - binary_sensor.template.publish:
          id: BMS_charging_ext
          state: !lambda 'return id(BMS_charging).state ;'
      - binary_sensor.template.publish:
          id: BMS_discharging_ext
          state: !lambda 'return id(BMS_discharging).state ;'
      - binary_sensor.template.publish:
          id: inverter_1600VA_fault_ext
          state: !lambda 'return id(inverter_1600_fault_state).state ;'
      - binary_sensor.template.publish:
          id: MPPT_100_30_Fault_state_ext
          state: !lambda 'return id(MPPT_100_30_Fault_state).state ;'
      - binary_sensor.template.publish:
          id: inverter_1600VA_Alarm_state_ext
          state: !lambda 'return id(inverter_1600_alarm_state).state ;'
      - binary_sensor.template.publish:
          id: inverter_1600_onoff_state_ext
          state: !lambda 'return id(inverter_1600_onoff_state).state ;'
      - binary_sensor.template.publish:
          id: MPPTerrortstate_ext
          state: !lambda 'return id(MPPT_100_30_error_state).state ;'       

  - interval: 90s
    then:
      - button.press: retrieve_BMS_settings
#      - lambda: |-
#          id(MPPTstate).publish_state(id(MPPTstate).state);

time:
  - platform: sntp
    id: sntp_time
    servers: "mifimiji.lacoume"
#    on_time:
#      # Every 5 minutes
#      - seconds: 0
#        minutes: /1
#        then:
#          - lambda: |-
#              id(MPPTstate).publish_state(id(MPPTstate).state);
button:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    # Retrieves the BMS settings and prints them in the ESPHome logs
    retrieve_settings:
      id: retrieve_BMS_settings
    retrieve_device_info:
      id: retrieve_BMS_info
    

  - platform: restart
    name: "restart esp32 microcontroller"

sensor:
  #daly bms 8 cells 24V 100A
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    #error_bitmask:
    #  name: "BMS error bitmask"
    total_voltage:
      name: "BMS total voltage"
      filters:
        - throttle: 30s
    current:
      name: "BMS current"
      filters:
        - throttle: 30s
    power:
      name: "BMS power"
      filters:
        - throttle: 30s
    charging_power:
      name: "BMS charging power"
      filters:
        - throttle: 30s
    discharging_power:
      name: "BMS discharging power"
      filters:
        - throttle: 30s
    state_of_charge:
      name: "BMS state of charge"
      filters:
        - throttle: 30s
    #charging_cycles:
    #  name: "BMS charging cycles"
    #min_cell_voltage:
    #  name: "BMS min cell voltage"
    #max_cell_voltage:
    #  name: "BMS max cell voltage"
    #min_voltage_cell:
    #  name: "BMS min voltage cell"
    #max_voltage_cell:
    #  name: "BMS max voltage cell"
    #delta_cell_voltage:
    #  name: "BMS delta cell voltage"
    #average_cell_voltage:
    #  name: "BMS average cell voltage"
    temperature_sensor_1:
      name: "BMS temperature 1"
      filters:
        - throttle: 30s
    temperature_sensor_2:
      name: "BMS temperature 2"
      filters:
        - throttle: 30s
#    temperature_3:
#      name: "${name} temperature 3"
#    temperature_4:
#      name: "${name} temperature 4"
#    temperature_5:
#      name: "${name} temperature 5"
#    temperature_6:
#      name: "${name} temperature 6"
#    temperature_7:
#      name: "${name} temperature 7"
#    temperature_8:
#      name: "${name} temperature 8"
    cell_voltage_1:
      name: "BMS cell voltage 1"
      filters:
        - throttle: 30s
    cell_voltage_2:
      name: "BMS cell voltage 2"
      filters:
        - throttle: 30s
    cell_voltage_3:
      name: "BMS cell voltage 3"
      filters:
        - throttle: 30s
    cell_voltage_4:
      name: "BMS cell voltage 4"
      filters:
        - throttle: 30s
    cell_voltage_5:
      name: "BMS cell voltage 5"
      filters:
        - throttle: 30s
    cell_voltage_6:
      name: "BMS cell voltage 6"
      filters:
        - throttle: 30s
    cell_voltage_7:
      name: "BMS cell voltage 7"
      filters:
        - throttle: 30s
    cell_voltage_8:
      name: "BMS cell voltage 8"
      filters:
        - throttle: 30s
#    cell_voltage_9:
#      name: "${name} cell voltage 9"
#    cell_voltage_10:
#      name: "${name} cell voltage 10"
#    cell_voltage_11:
#      name: "${name} cell voltage 11"
#    cell_voltage_12:
#      name: "${name} cell voltage 12"
#    cell_voltage_13:
#      name: "${name} cell voltage 13"
#    cell_voltage_14:
#      name: "${name} cell voltage 14"
#    cell_voltage_15:
#      name: "${name} cell voltage 15"
#    cell_voltage_16:
#      name: "${name} cell voltage 16"
    #cell_count:
    #  name: "BMS cell count"
    #temperature_sensors:
    #  name: "BMS temperature sensors"
    capacity_remaining:
      name: "BMS capacity remaining"
      filters:
        - throttle: 60s
  #wifi signal
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  # lacoumeSmartSolar
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar
    id: MPPT_BAT_VOLTAGE
    name: "MPPT 100-30 Battery Voltage"
    filters:
      - throttle: 30s
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    id: MPPT_BAT_CURRENT
    victron_ble_id: lacoumeSmartSolar
    name: "MPPT 100-30 Battery Current"
    filters:
      - throttle: 30s
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar
    filters:
      - throttle: 30s
    name: "MPPT 100-30 Yield Today"
    type: YIELD_TODAY
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar
    filters:
      - throttle: 30s
    name: "MPPT 100-30 PV Power"
    type: PV_POWER
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar
    filters:
      - throttle: 30s
    name: "MPPT 100-30 Load Current"
    type: LOAD_CURRENT
  # inverter 1600VA
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: lacoume1600VA
    name: "inverter1600VA AC Apparent power"
    type: AC_APPARENT_POWER
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: lacoume1600VA
    name: "inverter1600VA AC current"
    type: AC_CURRENT
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: lacoume1600VA
    name: "inverter1600VA AC voltage"
    type: AC_VOLTAGE
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: lacoume1600VA
    name: "inverter1600VA Alarm reason"
    type: ALARM_REASON
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: lacoume1600VA
    name: "inverter1600VA Battery voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: lacoume1600VA
    name: "inverter1600VA Device state"
    type: DEVICE_STATE

  # bmv700
  #- platform: victron_ble
  #  victron_ble_id: bmv700
  #  name: "Time remaining"
  #  type: TIME_TO_GO
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: bmv700
    id: BMV700_VOLTAGE
    name: "BMV700 Battery Voltage"
    type: BATTERY_VOLTAGE
  #- platform: victron_ble
    #victron_ble_id: bmv700
    #name: "Starter Battery Voltage"
    # AUX_VOLTAGE or MID_VOLTAGE or TEMPERATURE.
    # Depending on configuration of SmartShunt.
    #type: AUX_VOLTAGE
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: bmv700
    id: BMV700_CURRENT
    name: "BMV700 Battery Current"
    type: BATTERY_CURRENT
  
  - platform: template
    name: "BMV700 calculated power"
    update_interval: 30s
    lambda: !lambda |-
      return (id(BMV700_CURRENT).state *id(BMV700_VOLTAGE).state);

  - platform: template
    name: "MPPT Battery calculated power"
    update_interval: 30s
    lambda: !lambda |-
      return (id(MPPT_BAT_VOLTAGE).state *id(MPPT_BAT_CURRENT).state);


  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: bmv700
    name: "BMV700 Consumed Ah"
    type: CONSUMED_AH
  - platform: victron_ble
    filters:
      - throttle: 30s
    victron_ble_id: bmv700
    name: "BMV700 State of charge"
    type: STATE_OF_CHARGE



text_sensor:
    #daly
  - platform: jk_bms_ble    
    jk_bms_ble_id: bms0
    errors:
      id: BMS_errors
  - platform: template
    update_interval: 30s
    id: BMS_errors_ext
    name: "BMS errors"
    lambda: !lambda |-
      return id(BMS_errors).state;
    #victron 


  # MPPT State victron
  - platform: victron_ble
    victron_ble_id: lacoumeSmartSolar
    id: MPPTstate
    type: DEVICE_STATE
  - platform: template
    update_interval: 30s
    id: MPPTstate_ext
    name: "MPPT 100-30 state"
    lambda: !lambda |-
      return id(MPPTstate).state;



  #- platform: victron_ble
  #  victron_ble_id: lacoumeSmartSolar
  #  name: "MPPT 100-30 Error reason"
  #  type: CHARGER_ERROR
  #- platform: victron_ble
  #  victron_ble_id: lacoume1600VA
  #  name: "Alarm reason"
  #  type: ALARM_REASON
  - platform: victron_ble
    victron_ble_id: lacoume1600VA
    id: lacoume1600VAStatus
    type: DEVICE_STATE
  - platform: template
    update_interval: 30s
    id: lacoume1600VAStatus_ext
    name: "lacoume1600va Status"
    lambda: !lambda |-
      return id(lacoume1600VAStatus).state;



number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${name} balance trigger voltage"
    cell_count:
      name: "${name} cell count"
    total_battery_capacity:
      name: "${name} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    voltage_calibration:
      name: "${name} voltage calibration"
    current_calibration:
      name: "${name} current calibration"
    power_off_voltage:
      name: "${name} power off voltage"
    max_balance_current:
      name: "${name} max balance current"
    max_charge_current:
      name: "${name} max charge current"
    max_discharge_current:
      name: "${name} max discharge current"
    smart_sleep_voltage:
      name: "${name} smart sleep voltage"
    cell_soc100_voltage:
      name: "${name} cell soc100 voltage"
    cell_soc0_voltage:
      name: "${name} cell soc0 voltage"
    cell_request_charge_voltage:
      name: "${name} cell request charge voltage"
    cell_request_float_voltage:
      name: "${name} cell request float voltage"
    charge_overcurrent_protection_delay:
      name: "${name} charge overcurrent protection delay"
    charge_overcurrent_protection_recovery_time:
      name: "${name} charge overcurrent protection recovery time"
    discharge_overcurrent_protection_delay:
      name: "${name} discharge overcurrent protection delay"
    discharge_overcurrent_protection_recovery_time:
      name: "${name} discharge overcurrent protection recovery time"
    short_circuit_protection_delay:
      name: "${name} short circuit protection delay"
    short_circuit_protection_recovery_time:
      name: "${name} short circuit protection recovery time"
    charge_overtemperature_protection:
      name: "${name} charge overtemperature protection"
    charge_overtemperature_protection_recovery:
      name: "${name} charge overtemperature protection recovery"
    discharge_overtemperature_protection:
      name: "${name} discharge overtemperature protection"
    discharge_overtemperature_protection_recovery:
      name: "${name} discharge overtemperature protection recovery"
    charge_undertemperature_protection:
      name: "${name} charge undertemperature protection"
    charge_undertemperature_protection_recovery:
      name: "${name} charge undertemperature protection recovery"
    power_tube_overtemperature_protection:
      name: "${name} power tube overtemperature protection"
    power_tube_overtemperature_protection_recovery:
      name: "${name} power tube overtemperature protection recovery"



switch:
  - platform: jk_bms_ble
  #  balancer:
  #   name: "BMS balancer"
    charging:
      name: "BMS charging"
    discharging:
      name: "BMS discharging"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "enable esp32 bluetooth connection" 
```
